-- UTF-8 olarak yeniden oluşturulmuştur.
-- Kaynak: Hâkimler ve Savcılar Kurulu, Adli Yargı Rehberi (13.08.2025).
-- Toplam kayıt: 1004

SET client_encoding = 'UTF8';

INSERT INTO public.adliye_rehberi (sira_no, name, bolge, teskilat_turu, faaliyet_durumu, bagli_oldugu_adliye, acm, il) VALUES
(1, 'Adana', 1, 'ACM', 'Faal', NULL, 'Adana', 'Adana'),
(2, 'Karaisalı', 4, 'Mülhakat', 'Faal', NULL, 'Adana', 'Adana'),
(3, 'Karataş', 3, 'Mülhakat', 'Faal', NULL, 'Adana', 'Adana'),
(4, 'Çukurova', NULL, NULL, 'Teşkilat Kurulmadı', 'Adana', 'Adana', 'Adana'),
(5, 'Sarıçam', NULL, NULL, 'Teşkilat Kurulmadı', 'Adana', 'Adana', 'Adana'),
(6, 'Seyhan', NULL, NULL, 'Teşkilat Kurulmadı', 'Adana', 'Adana', 'Adana'),
(7, 'Yüreğir', NULL, NULL, 'Teşkilat Kurulmadı', 'Adana', 'Adana', 'Adana'),
(8, 'Adıyaman', 2, 'ACM', 'Faal', NULL, 'Adıyaman', 'Adıyaman'),
(9, 'Besni', 4, 'Mülhakat', 'Faal', NULL, 'Adıyaman', 'Adıyaman'),
(10, 'Gerger', 5, 'Mülhakat', 'Faal', NULL, 'Adıyaman', 'Adıyaman'),
(11, 'Gölbaşı (Adıyaman)', 3, 'Mülhakat', 'Faal', NULL, 'Adıyaman', 'Adıyaman'),
(12, 'Kâhta', 3, 'Mülhakat', 'Faal', NULL, 'Adıyaman', 'Adıyaman'),
(13, 'Çelikhan', NULL, NULL, 'Birleştirildi', 'Adıyaman', 'Adıyaman', 'Adıyaman'),
(14, 'Samsat', NULL, NULL, 'Birleştirildi', 'Adıyaman', 'Adıyaman', 'Adıyaman'),
(15, 'Sincik', NULL, NULL, 'Birleştirildi', 'Kâhta', 'Adıyaman', 'Adıyaman'),
(16, 'Tut', NULL, NULL, 'Birleştirildi', 'Gölbaşı (Adıyaman)', 'Adıyaman', 'Adıyaman'),
(17, 'Afyonkarahisar', 1, 'ACM', 'Faal', NULL, 'Afyonkarahisar', 'Afyonkarahisar'),
(18, 'İscehisar', 4, 'Mülhakat', 'Faal', NULL, 'Afyonkarahisar', 'Afyonkarahisar'),
(19, 'Sandıklı', 3, 'Mülhakat', 'Faal', NULL, 'Afyonkarahisar', 'Afyonkarahisar'),
(20, 'Sinanpaşa', 4, 'Mülhakat', 'Faal', NULL, 'Afyonkarahisar', 'Afyonkarahisar'),
(21, 'Şuhut', 4, 'Mülhakat', 'Faal', NULL, 'Afyonkarahisar', 'Afyonkarahisar'),
(22, 'Bayat (Afyonkarahisar)', NULL, NULL, 'Birleştirildi', 'İscehisar', 'Afyonkarahisar', 'Afyonkarahisar'),
(23, 'Çobanlar', NULL, NULL, 'Birleştirildi', 'Afyonkarahisar', 'Afyonkarahisar', 'Afyonkarahisar'),
(24, 'Hocalar', NULL, NULL, 'Birleştirildi', 'Sandıklı', 'Afyonkarahisar', 'Afyonkarahisar'),
(25, 'İhsaniye', NULL, NULL, 'Birleştirildi', 'Afyonkarahisar', 'Afyonkarahisar', 'Afyonkarahisar'),
(26, 'Kızılören', NULL, NULL, 'Teşkilat Kurulmadı', 'Sandıklı', 'Afyonkarahisar', 'Afyonkarahisar'),
(27, 'Ağrı', 3, 'ACM', 'Faal', NULL, 'Ağrı', 'Ağrı'),
(28, 'Eleşkirt', 4, 'Mülhakat', 'Faal', NULL, 'Ağrı', 'Ağrı'),
(29, 'Taşlıçay', 5, 'Mülhakat', 'Faal', NULL, 'Ağrı', 'Ağrı'),
(30, 'Hamur', NULL, NULL, 'Birleştirildi', 'Ağrı', 'Ağrı', 'Ağrı'),
(31, 'Akhisar', 2, 'ACM', 'Faal', NULL, 'Akhisar', 'Manisa'),
(32, 'Gördes', 3, 'Mülhakat', 'Faal', NULL, 'Akhisar', 'Manisa'),
(33, 'Gölmarmara', NULL, NULL, 'Birleştirildi', 'Akhisar', 'Akhisar', 'Manisa'),
(34, 'Aksaray', 1, 'ACM', 'Faal', NULL, 'Aksaray', 'Aksaray'),
(35, 'Eskil', 4, 'Mülhakat', 'Faal', NULL, 'Aksaray', 'Aksaray'),
(36, 'Ortaköy (Aksaray)', 3, 'Mülhakat', 'Faal', NULL, 'Aksaray', 'Aksaray'),
(37, 'Şereflikoçhisar', 3, 'Mülhakat', 'Faal', NULL, 'Aksaray', 'Ankara'),
(38, 'Ağaçören', NULL, NULL, 'Birleştirildi', 'Ortaköy (Aksaray)', 'Aksaray', 'Aksaray'),
(39, 'Evren', NULL, NULL, 'Birleştirildi', 'Şereflikoçhisar', 'Aksaray', 'Ankara'),
(40, 'Gülağaç', NULL, NULL, 'Birleştirildi', 'Aksaray', 'Aksaray', 'Aksaray'),
(41, 'Güzelyurt', NULL, NULL, 'Birleştirildi', 'Aksaray', 'Aksaray', 'Aksaray'),
(42, 'Sarıyahşi', NULL, NULL, 'Birleştirildi', 'Şereflikoçhisar', 'Aksaray', 'Aksaray'),
(43, 'Sultanhanı', NULL, NULL, 'Teşkilat Kurulmadı', 'Aksaray', 'Aksaray', 'Aksaray'),
(44, 'Akşehir', 2, 'ACM', 'Faal', NULL, 'Akşehir', 'Konya'),
(45, 'Doğanhisar', 4, 'Mülhakat', 'Faal', NULL, 'Akşehir', 'Konya'),
(46, 'Ilgın', 3, 'Mülhakat', 'Faal', NULL, 'Akşehir', 'Konya'),
(47, 'Yunak', 4, 'Mülhakat', 'Faal', NULL, 'Akşehir', 'Konya'),
(48, 'Çeltik', NULL, NULL, 'Birleştirildi', 'Yunak', 'Akşehir', 'Konya'),
(49, 'Tuzlukçu', NULL, NULL, 'Birleştirildi', 'Akşehir', 'Akşehir', 'Konya'),
(50, 'Alanya', 1, 'ACM', 'Faal', NULL, 'Alanya', 'Antalya'),
(51, 'Gazipaşa', 3, 'Mülhakat', 'Faal', NULL, 'Alanya', 'Antalya'),
(52, 'Alaşehir', 2, 'ACM', 'Faal', NULL, 'Alaşehir', 'Manisa'),
(53, 'Sarıgöl', 3, 'Mülhakat', 'Faal', NULL, 'Alaşehir', 'Manisa'),
(54, 'Amasya', 2, 'ACM', 'Faal', NULL, 'Amasya', 'Amasya'),
(55, 'Gümüşhacıköy', 4, 'Mülhakat', 'Faal', NULL, 'Amasya', 'Amasya'),
(56, 'Merzifon', 2, 'Mülhakat', 'Faal', NULL, 'Amasya', 'Amasya'),
(57, 'Suluova', 3, 'Mülhakat', 'Faal', NULL, 'Amasya', 'Amasya'),
(58, 'Taşova', 3, 'Mülhakat', 'Faal', NULL, 'Amasya', 'Amasya'),
(59, 'Göynücek', NULL, NULL, 'Birleştirildi', 'Amasya', 'Amasya', 'Amasya'),
(60, 'Hamamözü', NULL, NULL, 'Teşkilat Kurulmadı', 'Gümüşhacıköy', 'Amasya', 'Amasya'),
(61, 'Anamur', 2, 'ACM', 'Faal', NULL, 'Anamur', 'Mersin'),
(62, 'Aydıncık', 3, 'Mülhakat', 'Faal', NULL, 'Anamur', 'Mersin'),
(63, 'Bozyazı', NULL, NULL, 'Birleştirildi', 'Anamur', 'Anamur', 'Mersin'),
(64, 'Ankara', 1, 'ACM', 'Faal', NULL, 'Ankara', 'Ankara'),
(65, 'Akyurt', 3, 'Mülhakat', 'Faal', NULL, 'Ankara', 'Ankara'),
(66, 'Balâ', 3, 'Mülhakat', 'Faal', NULL, 'Ankara', 'Ankara'),
(67, 'Çubuk', 2, 'Mülhakat', 'Faal', NULL, 'Ankara', 'Ankara'),
(68, 'Elmadağ', 2, 'Mülhakat', 'Faal', NULL, 'Ankara', 'Ankara'),
(69, 'Gölbaşı (Ankara)', 1, 'Mülhakat', 'Faal', NULL, 'Ankara', 'Ankara'),
(70, 'Haymana', 3, 'Mülhakat', 'Faal', NULL, 'Ankara', 'Ankara'),
(71, 'Kalecik', 3, 'Mülhakat', 'Faal', NULL, 'Ankara', 'Ankara'),
(72, 'Altındağ', NULL, NULL, 'Teşkilat Kurulmadı', 'Ankara', 'Ankara', 'Ankara'),
(73, 'Çankaya', NULL, NULL, 'Teşkilat Kurulmadı', 'Ankara', 'Ankara', 'Ankara'),
(74, 'Keçiören', NULL, NULL, 'Teşkilat Kurulmadı', 'Ankara', 'Ankara', 'Ankara'),
(75, 'Mamak', NULL, NULL, 'Teşkilat Kurulmadı', 'Ankara', 'Ankara', 'Ankara'),
(76, 'Pursaklar', NULL, NULL, 'Teşkilat Kurulmadı', 'Ankara', 'Ankara', 'Ankara'),
(77, 'Yenimahalle', NULL, NULL, 'Teşkilat Kurulmadı', 'Ankara', 'Ankara', 'Ankara'),
(78, 'Ankara Batı', 1, 'ACM', 'Faal', NULL, 'Ankara Batı', 'Ankara'),
(79, 'Beypazarı', 2, 'Mülhakat', 'Faal', NULL, 'Ankara Batı', 'Ankara'),
(80, 'Kahramankazan', 2, 'Mülhakat', 'Faal', NULL, 'Ankara Batı', 'Ankara'),
(81, 'Kızılcahamam', 2, 'Mülhakat', 'Faal', NULL, 'Ankara Batı', 'Ankara'),
(82, 'Nallıhan', 4, 'Mülhakat', 'Faal', NULL, 'Ankara Batı', 'Ankara'),
(83, 'Ayaş', NULL, NULL, 'Birleştirildi', 'Ankara Batı', 'Ankara Batı', 'Ankara'),
(84, 'Çamlıdere', NULL, NULL, 'Birleştirildi', 'Kızılcahamam', 'Ankara Batı', 'Ankara'),
(85, 'Etimesgut', NULL, NULL, 'Teşkilat Kurulmadı', 'Ankara Batı', 'Ankara Batı', 'Ankara'),
(86, 'Güdül', NULL, NULL, 'Birleştirildi', 'Beypazarı', 'Ankara Batı', 'Ankara'),
(87, 'Antalya', 1, 'ACM', 'Faal', NULL, 'Antalya', 'Antalya'),
(88, 'Kemer', 2, 'Mülhakat', 'Faal', NULL, 'Antalya', 'Antalya'),
(89, 'Korkuteli', 3, 'Mülhakat', 'Faal', NULL, 'Antalya', 'Antalya'),
(90, 'Aksu (Antalya)', NULL, NULL, 'Teşkilat Kurulmadı', 'Antalya', 'Antalya', 'Antalya'),
(91, 'Döşemealtı', NULL, NULL, 'Teşkilat Kurulmadı', 'Antalya', 'Antalya', 'Antalya'),
(92, 'Kepez', NULL, NULL, 'Teşkilat Kurulmadı', 'Antalya', 'Antalya', 'Antalya'),
(93, 'Konyaaltı', NULL, NULL, 'Teşkilat Kurulmadı', 'Antalya', 'Antalya', 'Antalya'),
(94, 'Muratpaşa', NULL, NULL, 'Teşkilat Kurulmadı', 'Antalya', 'Antalya', 'Antalya'),
(95, 'Ardahan', 3, 'ACM', 'Faal', NULL, 'Ardahan', 'Ardahan'),
(96, 'Göle', 4, 'Mülhakat', 'Faal', NULL, 'Ardahan', 'Ardahan'),
(97, 'Hanak', 5, 'Mülhakat', 'Faal', NULL, 'Ardahan', 'Ardahan'),
(98, 'Posof', 5, 'Mülhakat', 'Faal', NULL, 'Ardahan', 'Ardahan'),
(99, 'Çıldır', NULL, NULL, 'Birleştirildi', 'Ardahan', 'Ardahan', 'Ardahan'),
(100, 'Damal', NULL, NULL, 'Birleştirildi', 'Hanak', 'Ardahan', 'Ardahan'),
(101, 'Artvin', 3, 'ACM', 'Faal', NULL, 'Artvin', 'Artvin'),
(102, 'Arhavi', 3, 'Mülhakat', 'Faal', NULL, 'Artvin', 'Artvin'),
(103, 'Borçka', 3, 'Mülhakat', 'Faal', NULL, 'Artvin', 'Artvin'),
(104, 'Hopa', 3, 'Mülhakat', 'Faal', NULL, 'Artvin', 'Artvin'),
(105, 'Şavşat', 5, 'Mülhakat', 'Faal', NULL, 'Artvin', 'Artvin'),
(106, 'Yusufeli', 5, 'Mülhakat', 'Faal', NULL, 'Artvin', 'Artvin'),
(107, 'Ardanuç', NULL, NULL, 'Birleştirildi', 'Artvin', 'Artvin', 'Artvin'),
(108, 'Kemalpaşa (Artvin)', NULL, NULL, 'Teşkilat Kurulmadı', 'Hopa', 'Artvin', 'Artvin'),
(109, 'Murgul', NULL, NULL, 'Faal Değil', 'Borçka', 'Artvin', 'Artvin'),
(110, 'Aydın', 1, 'ACM', 'Faal', NULL, 'Aydın', 'Aydın'),
(111, 'Çine', 3, 'Mülhakat', 'Faal', NULL, 'Aydın', 'Aydın'),
(112, 'Germencik', 3, 'Mülhakat', 'Faal', NULL, 'Aydın', 'Aydın'),
(113, 'Efeler', NULL, NULL, 'Teşkilat Kurulmadı', 'Aydın', 'Aydın', 'Aydın'),
(114, 'İncirliova', NULL, NULL, 'Birleştirildi', 'Aydın', 'Aydın', 'Aydın'),
(115, 'Karpuzlu', NULL, NULL, 'Birleştirildi', 'Çine', 'Aydın', 'Aydın'),
(116, 'Koçarlı', NULL, NULL, 'Birleştirildi', 'Aydın', 'Aydın', 'Aydın'),
(117, 'Köşk', NULL, NULL, 'Birleştirildi', 'Aydın', 'Aydın', 'Aydın'),
(118, 'Bafra', 2, 'ACM', 'Faal', NULL, 'Bafra', 'Samsun'),
(119, 'Alaçam', 3, 'Mülhakat', 'Faal', NULL, 'Bafra', 'Samsun'),
(120, 'Ondokuz Mayıs', NULL, NULL, 'Birleştirildi', 'Bafra', 'Bafra', 'Samsun'),
(121, 'Yakakent', NULL, NULL, 'Teşkilat Kurulmadı', 'Alaçam', 'Bafra', 'Samsun'),
(122, 'Bakırköy', 1, 'ACM', 'Faal', NULL, 'Bakırköy', 'İstanbul'),
(123, 'Büyükçekmece', 1, 'Mülhakat', 'Faal', NULL, 'Bakırköy', 'İstanbul'),
(124, 'Bağcılar', NULL, NULL, 'Birleştirildi', 'Bakırköy', 'Bakırköy', 'İstanbul'),
(125, 'Bahçelievler', NULL, NULL, 'Teşkilat Kurulmadı', 'Bakırköy', 'Bakırköy', 'İstanbul'),
(126, 'Beylikdüzü', NULL, NULL, 'Teşkilat Kurulmadı', 'Büyükçekmece', 'Bakırköy', 'İstanbul'),
(127, 'Esenler', NULL, NULL, 'Teşkilat Kurulmadı', 'Bakırköy', 'Bakırköy', 'İstanbul'),
(128, 'Esenyurt', NULL, NULL, 'Teşkilat Kurulmadı', 'Büyükçekmece', 'Bakırköy', 'İstanbul'),
(129, 'Güngören', NULL, NULL, 'Teşkilat Kurulmadı', 'Bakırköy', 'Bakırköy', 'İstanbul'),
(130, 'Zeytinburnu', NULL, NULL, 'Birleştirildi', 'Bakırköy', 'Bakırköy', 'İstanbul'),
(131, 'Balıkesir', 1, 'ACM', 'Faal', NULL, 'Balıkesir', 'Balıkesir'),
(132, 'Bigadiç', 3, 'Mülhakat', 'Faal', NULL, 'Balıkesir', 'Balıkesir'),
(133, 'Dursunbey', 3, 'Mülhakat', 'Faal', NULL, 'Balıkesir', 'Balıkesir'),
(134, 'İvrindi', 3, 'Mülhakat', 'Faal', NULL, 'Balıkesir', 'Balıkesir'),
(135, 'Kepsut', 3, 'Mülhakat', 'Faal', NULL, 'Balıkesir', 'Balıkesir'),
(136, 'Savaştepe', 3, 'Mülhakat', 'Faal', NULL, 'Balıkesir', 'Balıkesir'),
(137, 'Sındırgı', 3, 'Mülhakat', 'Faal', NULL, 'Balıkesir', 'Balıkesir'),
(138, 'Susurluk', 3, 'Mülhakat', 'Faal', NULL, 'Balıkesir', 'Balıkesir'),
(139, 'Altıeylül', NULL, NULL, 'Teşkilat Kurulmadı', 'Balıkesir', 'Balıkesir', 'Balıkesir'),
(140, 'Balya', NULL, NULL, 'Birleştirildi', 'İvrindi', 'Balıkesir', 'Balıkesir'),
(141, 'Karesi', NULL, NULL, 'Teşkilat Kurulmadı', 'Balıkesir', 'Balıkesir', 'Balıkesir'),
(142, 'Bandırma', 2, 'ACM', 'Faal', NULL, 'Bandırma', 'Balıkesir'),
(143, 'Erdek', 2, 'Mülhakat', 'Faal', NULL, 'Bandırma', 'Balıkesir'),
(144, 'Gönen', 2, 'Mülhakat', 'Faal', NULL, 'Bandırma', 'Balıkesir'),
(145, 'Manyas', 4, 'Mülhakat', 'Faal', NULL, 'Bandırma', 'Balıkesir'),
(146, 'Marmara', 4, 'Mülhakat', 'Faal', NULL, 'Bandırma', 'Balıkesir'),
(147, 'Bartın', 2, 'ACM', 'Faal', NULL, 'Bartın', 'Bartın'),
(148, 'Amasra', 3, 'Mülhakat', 'Faal', NULL, 'Bartın', 'Bartın'),
(149, 'Ulus', 4, 'Mülhakat', 'Faal', NULL, 'Bartın', 'Bartın'),
(150, 'Kurucaşile', NULL, NULL, 'Birleştirildi', 'Amasra', 'Bartın', 'Bartın'),
(151, 'Batman', 2, 'ACM', 'Faal', NULL, 'Batman', 'Batman'),
(152, 'Kozluk', 5, 'Mülhakat', 'Faal', NULL, 'Batman', 'Batman'),
(153, 'Sason', 5, 'Mülhakat', 'Faal', NULL, 'Batman', 'Batman'),
(154, 'Beşiri', NULL, NULL, 'Birleştirildi', 'Batman', 'Batman', 'Batman'),
(155, 'Hasankeyf', NULL, NULL, 'Teşkilat Kurulmadı', 'Batman', 'Batman', 'Batman'),
(156, 'Bayburt', 3, 'ACM', 'Faal', NULL, 'Bayburt', 'Bayburt'),
(157, 'Aydıntepe', NULL, NULL, 'Birleştirildi', 'Bayburt', 'Bayburt', 'Bayburt'),
(158, 'Demirözü', NULL, NULL, 'Birleştirildi', 'Bayburt', 'Bayburt', 'Bayburt'),
(159, 'Bergama', 2, 'ACM', 'Faal', NULL, 'Bergama', 'İzmir'),
(160, 'Dikili', 2, 'Mülhakat', 'Faal', NULL, 'Bergama', 'İzmir'),
(161, 'Kınık', 3, 'Mülhakat', 'Faal', NULL, 'Bergama', 'İzmir'),
(162, 'Biga', 2, 'ACM', 'Faal', NULL, 'Biga', 'Çanakkale'),
(163, 'Çan', 3, 'Mülhakat', 'Faal', NULL, 'Biga', 'Çanakkale'),
(164, 'Yenice (Çanakkale)', 4, 'Mülhakat', 'Faal', NULL, 'Biga', 'Çanakkale'),
(165, 'Bilecik', 2, 'ACM', 'Faal', NULL, 'Bilecik', 'Bilecik'),
(166, 'Bozüyük', 2, 'Mülhakat', 'Faal', NULL, 'Bilecik', 'Bilecik'),
(167, 'Gölpazarı', 4, 'Mülhakat', 'Faal', NULL, 'Bilecik', 'Bilecik'),
(168, 'İnönü (FD)', 3, 'Mülhakat', 'Birleştirildi', 'Bozüyük', 'Bilecik', 'Eskişehir'),
(169, 'Osmaneli', 3, 'Mülhakat', 'Faal', NULL, 'Bilecik', 'Bilecik'),
(170, 'Söğüt', 3, 'Mülhakat', 'Faal', NULL, 'Bilecik', 'Bilecik'),
(171, 'İnhisar', NULL, NULL, 'Birleştirildi', 'Söğüt', 'Bilecik', 'Bilecik'),
(172, 'Pazaryeri', NULL, NULL, 'Birleştirildi', 'Bozüyük', 'Bilecik', 'Bilecik'),
(173, 'Yenipazar (Bilecik)', NULL, NULL, 'Birleştirildi', 'Gölpazarı', 'Bilecik', 'Bilecik'),
(174, 'Bingöl', 3, 'ACM', 'Faal', NULL, 'Bingöl', 'Bingöl'),
(175, 'Genç', 4, 'Mülhakat', 'Faal', NULL, 'Bingöl', 'Bingöl'),
(176, 'Karlıova', 5, 'Mülhakat', 'Faal', NULL, 'Bingöl', 'Bingöl'),
(177, 'Kiğı', 5, 'Mülhakat', 'Faal', NULL, 'Bingöl', 'Bingöl'),
(178, 'Solhan', 5, 'Mülhakat', 'Faal', NULL, 'Bingöl', 'Bingöl'),
(179, 'Adaklı', NULL, NULL, 'Birleştirildi', 'Kiğı', 'Bingöl', 'Bingöl'),
(180, 'Yedisu', NULL, NULL, 'Birleştirildi', 'Karlıova', 'Bingöl', 'Bingöl'),
(181, 'Birecik', 3, 'ACM', 'Faal', NULL, 'Birecik', 'Şanlıurfa'),
(182, 'Halfeti', 5, 'Mülhakat', 'Faal', NULL, 'Birecik', 'Şanlıurfa'),
(183, 'Bismil', 3, 'ACM', 'Faal', NULL, 'Bismil', 'Diyarbakır'),
(184, 'Bitlis', 3, 'ACM', 'Faal', NULL, 'Bitlis', 'Bitlis'),
(185, 'Güroymak', 4, 'Mülhakat', 'Faal', NULL, 'Bitlis', 'Bitlis'),
(186, 'Mutki', 5, 'Mülhakat', 'Faal', NULL, 'Bitlis', 'Bitlis'),
(187, 'Bodrum', 1, 'ACM', 'Faal', NULL, 'Bodrum', 'Muğla'),
(188, 'Boğazlıyan', 3, 'ACM', 'Faal', NULL, 'Boğazlıyan', 'Yozgat'),
(189, 'Çayıralan', 4, 'Mülhakat', 'Faal', NULL, 'Boğazlıyan', 'Yozgat'),
(190, 'Sarıkaya', 3, 'Mülhakat', 'Faal', NULL, 'Boğazlıyan', 'Yozgat'),
(191, 'Çandır', NULL, NULL, 'Birleştirildi', 'Çayıralan', 'Boğazlıyan', 'Yozgat'),
(192, 'Yenifakılı', NULL, NULL, 'Birleştirildi', 'Boğazlıyan', 'Boğazlıyan', 'Yozgat'),
(193, 'Bolu', 1, 'ACM', 'Faal', NULL, 'Bolu', 'Bolu'),
(194, 'Gerede', 2, 'Mülhakat', 'Faal', NULL, 'Bolu', 'Bolu'),
(195, 'Göynük', 4, 'Mülhakat', 'Faal', NULL, 'Bolu', 'Bolu'),
(196, 'Mengen', 3, 'Mülhakat', 'Faal', NULL, 'Bolu', 'Bolu'),
(197, 'Mudurnu', 3, 'Mülhakat', 'Faal', NULL, 'Bolu', 'Bolu'),
(198, 'Dörtdivan', NULL, NULL, 'Birleştirildi', 'Gerede', 'Bolu', 'Bolu'),
(199, 'Kıbrıscık', NULL, NULL, 'Birleştirildi', 'Bolu', 'Bolu', 'Bolu'),
(200, 'Seben', NULL, NULL, 'Birleştirildi', 'Bolu', 'Bolu', 'Bolu'),
(201, 'Yeniçağa', NULL, NULL, 'Birleştirildi', 'Gerede', 'Bolu', 'Bolu'),
(202, 'Bolvadin', 3, 'ACM', 'Faal', NULL, 'Bolvadin', 'Afyonkarahisar'),
(203, 'Çay', 3, 'Mülhakat', 'Faal', NULL, 'Bolvadin', 'Afyonkarahisar'),
(204, 'Emirdağ', 3, 'Mülhakat', 'Faal', NULL, 'Bolvadin', 'Afyonkarahisar'),
(205, 'Sultandağı', NULL, NULL, 'Birleştirildi', 'Çay', 'Bolvadin', 'Afyonkarahisar'),
(206, 'Boyabat', 3, 'ACM', 'Faal', NULL, 'Boyabat', 'Sinop'),
(207, 'Durağan', 4, 'Mülhakat', 'Faal', NULL, 'Boyabat', 'Sinop'),
(208, 'Saraydüzü', NULL, NULL, 'Birleştirildi', 'Boyabat', 'Boyabat', 'Sinop'),
(209, 'Burdur', 2, 'ACM', 'Faal', NULL, 'Burdur', 'Burdur'),
(210, 'Bucak', 2, 'Mülhakat', 'Faal', NULL, 'Burdur', 'Burdur'),
(211, 'Gölhisar', 3, 'Mülhakat', 'Faal', NULL, 'Burdur', 'Burdur'),
(212, 'Tefenni', 4, 'Mülhakat', 'Faal', NULL, 'Burdur', 'Burdur'),
(213, 'Yeşilova', 4, 'Mülhakat', 'Faal', NULL, 'Burdur', 'Burdur'),
(214, 'Ağlasun', NULL, NULL, 'Birleştirildi', 'Burdur', 'Burdur', 'Burdur'),
(215, 'Altınyayla (Burdur)', NULL, NULL, 'Birleştirildi', 'Gölhisar', 'Burdur', 'Burdur'),
(216, 'Çavdır', NULL, NULL, 'Birleştirildi', 'Gölhisar', 'Burdur', 'Burdur'),
(217, 'Çeltikçi', NULL, NULL, 'Birleştirildi', 'Bucak', 'Burdur', 'Burdur'),
(218, 'Karamanlı', NULL, NULL, 'Birleştirildi', 'Tefenni', 'Burdur', 'Burdur'),
(219, 'Kemer (Burdur)', NULL, NULL, 'Birleştirildi', 'Burdur', 'Burdur', 'Burdur'),
(220, 'Burhaniye', 2, 'ACM', 'Faal', NULL, 'Burhaniye', 'Balıkesir'),
(221, 'Ayvalık', 2, 'Mülhakat', 'Faal', NULL, 'Burhaniye', 'Balıkesir'),
(222, 'Edremit', 2, 'Mülhakat', 'Faal', NULL, 'Burhaniye', 'Balıkesir'),
(223, 'Gömeç', NULL, NULL, 'Birleştirildi', 'Burhaniye', 'Burhaniye', 'Balıkesir'),
(224, 'Havran', NULL, NULL, 'Birleştirildi', 'Edremit', 'Burhaniye', 'Balıkesir'),
(225, 'Bursa', 1, 'ACM', 'Faal', NULL, 'Bursa', 'Bursa'),
(226, 'Keles', 4, 'Mülhakat', 'Faal', NULL, 'Bursa', 'Bursa'),
(227, 'Mudanya', 2, 'Mülhakat', 'Faal', NULL, 'Bursa', 'Bursa'),
(228, 'Orhaneli', 3, 'Mülhakat', 'Faal', NULL, 'Bursa', 'Bursa'),
(229, 'Büyükorhan', NULL, NULL, 'Birleştirildi', 'Orhaneli', 'Bursa', 'Bursa'),
(230, 'Gürsu', NULL, NULL, 'Birleştirildi', 'Bursa', 'Bursa', 'Bursa'),
(231, 'Kestel', NULL, NULL, 'Birleştirildi', 'Bursa', 'Bursa', 'Bursa'),
(232, 'Nilüfer', NULL, NULL, 'Faal Değil', 'Bursa', 'Bursa', 'Bursa'),
(233, 'Osmangazi', NULL, NULL, 'Teşkilat Kurulmadı', 'Bursa', 'Bursa', 'Bursa'),
(234, 'Yıldırım', NULL, NULL, 'Faal Değil', 'Bursa', 'Bursa', 'Bursa'),
(235, 'Ceyhan', 2, 'ACM', 'Faal', NULL, 'Ceyhan', 'Adana'),
(236, 'Yumurtalık', 3, 'Mülhakat', 'Faal', NULL, 'Ceyhan', 'Adana'),
(237, 'Cizre', 3, 'ACM', 'Faal', NULL, 'Cizre', 'Şırnak'),
(238, 'İdil', 5, 'Mülhakat', 'Faal', NULL, 'Cizre', 'Şırnak'),
(239, 'Silopi', 3, 'Mülhakat', 'Faal', NULL, 'Cizre', 'Şırnak'),
(240, 'Güçlükonak', NULL, NULL, 'Teşkilat Kurulmadı', 'Cizre', 'Cizre', 'Şırnak'),
(241, 'Çanakkale', 1, 'ACM', 'Faal', NULL, 'Çanakkale', 'Çanakkale'),
(242, 'Ayvacık', 3, 'Mülhakat', 'Faal', NULL, 'Çanakkale', 'Çanakkale'),
(243, 'Bayramiç', 3, 'Mülhakat', 'Faal', NULL, 'Çanakkale', 'Çanakkale'),
(244, 'Ezine', 3, 'Mülhakat', 'Faal', NULL, 'Çanakkale', 'Çanakkale'),
(245, 'Gelibolu', 2, 'Mülhakat', 'Faal', NULL, 'Çanakkale', 'Çanakkale'),
(246, 'Gökçeada', 4, 'Mülhakat', 'Faal', NULL, 'Çanakkale', 'Çanakkale'),
(247, 'Lâpseki', 3, 'Mülhakat', 'Faal', NULL, 'Çanakkale', 'Çanakkale'),
(248, 'Bozcaada', NULL, NULL, 'Birleştirildi', 'Ezine', 'Çanakkale', 'Çanakkale'),
(249, 'Eceabat', NULL, NULL, 'Birleştirildi', 'Çanakkale', 'Çanakkale', 'Çanakkale'),
(250, 'Çankırı', 2, 'ACM', 'Faal', NULL, 'Çankırı', 'Çankırı'),
(251, 'Ilgaz', 3, 'Mülhakat', 'Faal', NULL, 'Çankırı', 'Çankırı'),
(252, 'Kurşunlu', 4, 'Mülhakat', 'Faal', NULL, 'Çankırı', 'Çankırı'),
(253, 'Şabanözü', 4, 'Mülhakat', 'Faal', NULL, 'Çankırı', 'Çankırı'),
(254, 'Atkaracalar', NULL, NULL, 'Teşkilat Kurulmadı', 'Kurşunlu', 'Çankırı', 'Çankırı'),
(255, 'Bayramören', NULL, NULL, 'Teşkilat Kurulmadı', 'Kurşunlu', 'Çankırı', 'Çankırı'),
(256, 'Eldivan', NULL, NULL, 'Birleştirildi', 'Çankırı', 'Çankırı', 'Çankırı'),
(257, 'Kızılırmak', NULL, NULL, 'Birleştirildi', 'Çankırı', 'Çankırı', 'Çankırı'),
(258, 'Korgun', NULL, NULL, 'Teşkilat Kurulmadı', 'Çankırı', 'Çankırı', 'Çankırı'),
(259, 'Orta', NULL, NULL, 'Birleştirildi', 'Şabanözü', 'Çankırı', 'Çankırı'),
(260, 'Yapraklı', NULL, NULL, 'Birleştirildi', 'Çankırı', 'Çankırı', 'Çankırı'),
(261, 'Çarşamba', 2, 'ACM', 'Faal', NULL, 'Çarşamba', 'Samsun'),
(262, 'Terme', 2, 'Mülhakat', 'Faal', NULL, 'Çarşamba', 'Samsun'),
(263, 'Ayvacık (Çarşamba)', NULL, NULL, 'Birleştirildi', 'Çarşamba', 'Çarşamba', 'Samsun'),
(264, 'Salıpazarı', NULL, NULL, 'Birleştirildi', 'Çarşamba', 'Çarşamba', 'Samsun'),
(265, 'Çerkezköy', 2, 'ACM', 'Faal', NULL, 'Çerkezköy', 'Tekirdağ'),
(266, 'Saray (Tekirdağ)', 3, 'Mülhakat', 'Faal', NULL, 'Çerkezköy', 'Tekirdağ'),
(267, 'Kapaklı', NULL, NULL, 'Teşkilat Kurulmadı', 'Çerkezköy', 'Çerkezköy', 'Tekirdağ'),
(268, 'Çeşme', 2, 'ACM', 'Faal', NULL, 'Çeşme', 'İzmir'),
(269, 'Karaburun', 3, 'Mülhakat', 'Faal', NULL, 'Çeşme', 'İzmir'),
(270, 'Çorlu', 1, 'ACM', 'Faal', NULL, 'Çorlu', 'Tekirdağ'),
(271, 'Marmaraereğlisi', 3, 'Mülhakat', 'Faal', NULL, 'Çorlu', 'Tekirdağ'),
(272, 'Ergene', NULL, NULL, 'Teşkilat Kurulmadı', 'Çorlu', 'Çorlu', 'Tekirdağ'),
(273, 'Çorum', 1, 'ACM', 'Faal', NULL, 'Çorum', 'Çorum'),
(274, 'Bayat', 4, 'Mülhakat', 'Faal', NULL, 'Çorum', 'Çorum'),
(275, 'İskilip', 3, 'Mülhakat', 'Faal', NULL, 'Çorum', 'Çorum'),
(276, 'Kargı', 4, 'Mülhakat', 'Faal', NULL, 'Çorum', 'Çorum'),
(277, 'Osmancık', 3, 'Mülhakat', 'Faal', NULL, 'Çorum', 'Çorum'),
(278, 'Dodurga', NULL, NULL, 'Birleştirildi', 'Osmancık', 'Çorum', 'Çorum'),
(279, 'Lâçin', NULL, NULL, 'Birleştirildi', 'Osmancık', 'Çorum', 'Çorum'),
(280, 'Mecitözü', NULL, NULL, 'Birleştirildi', 'Çorum', 'Çorum', 'Çorum'),
(281, 'Oğuzlar', NULL, NULL, 'Birleştirildi', 'Çorum', 'Çorum', 'Çorum'),
(282, 'Ortaköy (Çorum)', NULL, NULL, 'Birleştirildi', 'Çorum', 'Çorum', 'Çorum'),
(283, 'Uğurludağ', NULL, NULL, 'Birleştirildi', 'İskilip', 'Çorum', 'Çorum'),
(284, 'Denizli', 1, 'ACM', 'Faal', NULL, 'Denizli', 'Denizli'),
(285, 'Acıpayam', 3, 'Mülhakat', 'Faal', NULL, 'Denizli', 'Denizli'),
(286, 'Buldan', 3, 'Mülhakat', 'Faal', NULL, 'Denizli', 'Denizli'),
(287, 'Çal', 3, 'Mülhakat', 'Faal', NULL, 'Denizli', 'Denizli'),
(288, 'Çameli', 4, 'Mülhakat', 'Faal', NULL, 'Denizli', 'Denizli'),
(289, 'Çardak', 3, 'Mülhakat', 'Faal', NULL, 'Denizli', 'Denizli'),
(290, 'Çivril', 3, 'Mülhakat', 'Faal', NULL, 'Denizli', 'Denizli'),
(291, 'Kale', 4, 'Mülhakat', 'Faal', NULL, 'Denizli', 'Denizli'),
(292, 'Sarayköy', 2, 'Mülhakat', 'Faal', NULL, 'Denizli', 'Denizli'),
(293, 'Tavas', 3, 'Mülhakat', 'Faal', NULL, 'Denizli', 'Denizli'),
(294, 'Babadağ', NULL, NULL, 'Birleştirildi', 'Sarayköy', 'Denizli', 'Denizli'),
(295, 'Baklan', NULL, NULL, 'Birleştirildi', 'Çal', 'Denizli', 'Denizli'),
(296, 'Bekilli', NULL, NULL, 'Birleştirildi', 'Çal', 'Denizli', 'Denizli'),
(297, 'Beyağaç', NULL, NULL, 'Birleştirildi', 'Kale', 'Denizli', 'Denizli'),
(298, 'Bozkurt (Denizli)', NULL, NULL, 'Birleştirildi', 'Çardak', 'Denizli', 'Denizli'),
(299, 'Güney', NULL, NULL, 'Birleştirildi', 'Buldan', 'Denizli', 'Denizli'),
(300, 'Honaz', NULL, NULL, 'Birleştirildi', 'Denizli', 'Denizli', 'Denizli'),
(301, 'Merkezefendi', NULL, NULL, 'Teşkilat Kurulmadı', 'Denizli', 'Denizli', 'Denizli'),
(302, 'Pamukkale', NULL, NULL, 'Birleştirildi', 'Denizli', 'Denizli', 'Denizli'),
(303, 'Serinhisar', NULL, NULL, 'Birleştirildi', 'Acıpayam', 'Denizli', 'Denizli'),
(304, 'Develi', 3, 'ACM', 'Faal', NULL, 'Develi', 'Kayseri'),
(305, 'Tomarza', 4, 'Mülhakat', 'Faal', NULL, 'Develi', 'Kayseri'),
(306, 'Yahyalı', 4, 'Mülhakat', 'Faal', NULL, 'Develi', 'Kayseri'),
(307, 'Yeşilhisar', 4, 'Mülhakat', 'Faal', NULL, 'Develi', 'Kayseri'),
(308, 'Dinar', 3, 'ACM', 'Faal', NULL, 'Dinar', 'Afyonkarahisar'),
(309, 'Dazkırı', 4, 'Mülhakat', 'Faal', NULL, 'Dinar', 'Afyonkarahisar'),
(310, 'Başmakçı', NULL, NULL, 'Birleştirildi', 'Dazkırı', 'Dinar', 'Afyonkarahisar'),
(311, 'Evciler', NULL, NULL, 'Faal Değil', 'Dazkırı', 'Dinar', 'Afyonkarahisar'),
(312, 'Diyarbakır', 1, 'ACM', 'Faal', NULL, 'Diyarbakır', 'Diyarbakır'),
(313, 'Çınar', 4, 'Mülhakat', 'Faal', NULL, 'Diyarbakır', 'Diyarbakır'),
(314, 'Eğil', 5, 'Mülhakat', 'Faal', NULL, 'Diyarbakır', 'Diyarbakır'),
(315, 'Hani', 5, 'Mülhakat', 'Faal', NULL, 'Diyarbakır', 'Diyarbakır'),
(316, 'Hazro', 5, 'Mülhakat', 'Faal', NULL, 'Diyarbakır', 'Diyarbakır'),
(317, 'Kulp', 5, 'Mülhakat', 'Faal', NULL, 'Diyarbakır', 'Diyarbakır'),
(318, 'Lice', 5, 'Mülhakat', 'Faal', NULL, 'Diyarbakır', 'Diyarbakır'),
(319, 'Silvan', 4, 'Mülhakat', 'Faal', NULL, 'Diyarbakır', 'Diyarbakır'),
(320, 'Bağlar', NULL, NULL, 'Teşkilat Kurulmadı', 'Diyarbakır', 'Diyarbakır', 'Diyarbakır'),
(321, 'Kayapınar', NULL, NULL, 'Teşkilat Kurulmadı', 'Diyarbakır', 'Diyarbakır', 'Diyarbakır'),
(322, 'Kocaköy', NULL, NULL, 'Birleştirildi', 'Diyarbakır', 'Diyarbakır', 'Diyarbakır'),
(323, 'Sur', NULL, NULL, 'Teşkilat Kurulmadı', 'Diyarbakır', 'Diyarbakır', 'Diyarbakır'),
(324, 'Yenişehir (Diyarbakır)', NULL, NULL, 'Teşkilat Kurulmadı', 'Diyarbakır', 'Diyarbakır', 'Diyarbakır'),
(325, 'Doğubayazıt', 3, 'ACM', 'Faal', NULL, 'Doğubayazıt', 'Ağrı'),
(326, 'Diyadin', 5, 'Mülhakat', 'Faal', NULL, 'Doğubayazıt', 'Ağrı'),
(327, 'Dörtyol', 2, 'ACM', 'Faal', NULL, 'Dörtyol', 'Hatay'),
(328, 'Erzin', 3, 'Mülhakat', 'Faal', NULL, 'Dörtyol', 'Hatay'),
(329, 'Payas', NULL, NULL, 'Teşkilat Kurulmadı', 'Dörtyol', 'Dörtyol', 'Hatay'),
(330, 'Düzce', 1, 'ACM', 'Faal', NULL, 'Düzce', 'Düzce'),
(331, 'Akçakoca', 3, 'Mülhakat', 'Faal', NULL, 'Düzce', 'Düzce'),
(332, 'Yığılca', 4, 'Mülhakat', 'Faal', NULL, 'Düzce', 'Düzce'),
(333, 'Cumayeri', NULL, NULL, 'Birleştirildi', 'Düzce', 'Düzce', 'Düzce'),
(334, 'Çilimli', NULL, NULL, 'Teşkilat Kurulmadı', 'Düzce', 'Düzce', 'Düzce'),
(335, 'Gölyaka', NULL, NULL, 'Birleştirildi', 'Düzce', 'Düzce', 'Düzce'),
(336, 'Gümüşova', NULL, NULL, 'Teşkilat Kurulmadı', 'Düzce', 'Düzce', 'Düzce'),
(337, 'Kaynaşlı', NULL, NULL, 'Teşkilat Kurulmadı', 'Düzce', 'Düzce', 'Düzce'),
(338, 'Edirne', 1, 'ACM', 'Faal', NULL, 'Edirne', 'Edirne'),
(339, 'Uzunköprü', 3, 'Mülhakat', 'Faal', NULL, 'Edirne', 'Edirne'),
(340, 'Havsa', NULL, NULL, 'Birleştirildi', 'Edirne', 'Edirne', 'Edirne'),
(341, 'Lalapaşa', NULL, NULL, 'Birleştirildi', 'Edirne', 'Edirne', 'Edirne'),
(342, 'Meriç', NULL, NULL, 'Birleştirildi', 'Uzunköprü', 'Edirne', 'Edirne'),
(343, 'Süloğlu', NULL, NULL, 'Faal Değil', 'Edirne', 'Edirne', 'Edirne'),
(344, 'Elazığ', 1, 'ACM', 'Faal', NULL, 'Elazığ', 'Elazığ'),
(345, 'Çemişgezek', 5, 'Mülhakat', 'Faal', NULL, 'Elazığ', 'Tunceli'),
(346, 'Karakoçan', 4, 'Mülhakat', 'Faal', NULL, 'Elazığ', 'Elazığ'),
(347, 'Keban', 4, 'Mülhakat', 'Faal', NULL, 'Elazığ', 'Elazığ'),
(348, 'Kovancılar', 4, 'Mülhakat', 'Faal', NULL, 'Elazığ', 'Elazığ'),
(349, 'Maden', 4, 'Mülhakat', 'Faal', NULL, 'Elazığ', 'Elazığ'),
(350, 'Palu', 4, 'Mülhakat', 'Faal', NULL, 'Elazığ', 'Elazığ'),
(351, 'Ağın', NULL, NULL, 'Birleştirildi', 'Keban', 'Elazığ', 'Elazığ'),
(352, 'Alacakaya', NULL, NULL, 'Birleştirildi', 'Maden', 'Elazığ', 'Elazığ'),
(353, 'Arıcak', NULL, NULL, 'Birleştirildi', 'Palu', 'Elazığ', 'Elazığ'),
(354, 'Baskil', NULL, NULL, 'Birleştirildi', 'Elazığ', 'Elazığ', 'Elazığ'),
(355, 'Sivrice', NULL, NULL, 'Birleştirildi', 'Elazığ', 'Elazığ', 'Elazığ'),
(356, 'Yayladere', NULL, NULL, 'Birleştirildi', 'Karakoçan', 'Elazığ', 'Bingöl'),
(357, 'Elbistan', 3, 'ACM', 'Faal', NULL, 'Elbistan', 'Kahramanmaraş'),
(358, 'Afşin', 3, 'Mülhakat', 'Faal', NULL, 'Elbistan', 'Kahramanmaraş'),
(359, 'Ekinözü', NULL, NULL, 'Birleştirildi', 'Elbistan', 'Elbistan', 'Kahramanmaraş'),
(360, 'Nurhak', NULL, NULL, 'Birleştirildi', 'Elbistan', 'Elbistan', 'Kahramanmaraş'),
(361, 'Elmalı', 3, 'ACM', 'Faal', NULL, 'Elmalı', 'Antalya'),
(362, 'Demre', 3, 'Mülhakat', 'Faal', NULL, 'Elmalı', 'Antalya'),
(363, 'Finike', 3, 'Mülhakat', 'Faal', NULL, 'Elmalı', 'Antalya'),
(364, 'Kaş', 3, 'Mülhakat', 'Faal', NULL, 'Elmalı', 'Antalya'),
(365, 'Kumluca', 3, 'Mülhakat', 'Faal', NULL, 'Elmalı', 'Antalya'),
(366, 'Erciş', 3, 'ACM', 'Faal', NULL, 'Erciş', 'Van'),
(367, 'Çaldıran', 5, 'Mülhakat', 'Faal', NULL, 'Erciş', 'Van'),
(368, 'Muradiye', 5, 'Mülhakat', 'Faal', NULL, 'Erciş', 'Van'),
(369, 'Ereğli (Konya)', 2, 'ACM', 'Faal', NULL, 'Ereğli (Konya)', 'Konya'),
(370, 'Karapınar', 3, 'Mülhakat', 'Faal', NULL, 'Ereğli (Konya)', 'Konya'),
(371, 'Emirgazi', NULL, NULL, 'Birleştirildi', 'Karapınar', 'Ereğli (Konya)', 'Konya'),
(372, 'Halkapınar', NULL, NULL, 'Teşkilat Kurulmadı', 'Ereğli (Konya)', 'Ereğli (Konya)', 'Konya'),
(373, 'Ereğli (Zonguldak)', 2, 'ACM', 'Faal', NULL, 'Ereğli (Zonguldak)', 'Zonguldak'),
(374, 'Alaplı', 3, 'Mülhakat', 'Faal', NULL, 'Ereğli (Zonguldak)', 'Zonguldak'),
(375, 'Ergani', 3, 'ACM', 'Faal', NULL, 'Ergani', 'Diyarbakır'),
(376, 'Çermik', 5, 'Mülhakat', 'Faal', NULL, 'Ergani', 'Diyarbakır'),
(377, 'Çüngüş', 5, 'Mülhakat', 'Faal', NULL, 'Ergani', 'Diyarbakır'),
(378, 'Dicle', 5, 'Mülhakat', 'Faal', NULL, 'Ergani', 'Diyarbakır'),
(379, 'Ermenek', 3, 'ACM', 'Faal', NULL, 'Ermenek', 'Karaman'),
(380, 'Sarıveliler', 5, 'Mülhakat', 'Faal', NULL, 'Ermenek', 'Karaman'),
(381, 'Başyayla', NULL, NULL, 'Birleştirildi', 'Ermenek', 'Ermenek', 'Karaman'),
(382, 'Erzincan', 2, 'ACM', 'Faal', NULL, 'Erzincan', 'Erzincan'),
(383, 'Çayırlı', 5, 'Mülhakat', 'Faal', NULL, 'Erzincan', 'Erzincan'),
(384, 'İliç', 5, 'Mülhakat', 'Faal', NULL, 'Erzincan', 'Erzincan'),
(385, 'Kemah', 4, 'Mülhakat', 'Faal', NULL, 'Erzincan', 'Erzincan'),
(386, 'Kemaliye', 5, 'Mülhakat', 'Faal', NULL, 'Erzincan', 'Erzincan'),
(387, 'Refahiye', 4, 'Mülhakat', 'Faal', NULL, 'Erzincan', 'Erzincan'),
(388, 'Tercan', 4, 'Mülhakat', 'Faal', NULL, 'Erzincan', 'Erzincan'),
(389, 'Otlukbeli', NULL, NULL, 'Birleştirildi', 'Çayırlı', 'Erzincan', 'Erzincan'),
(390, 'Üzümlü', NULL, NULL, 'Birleştirildi', 'Erzincan', 'Erzincan', 'Erzincan'),
(391, 'Erzurum', 1, 'ACM', 'Faal', NULL, 'Erzurum', 'Erzurum'),
(392, 'Aşkale', 4, 'Mülhakat', 'Faal', NULL, 'Erzurum', 'Erzurum'),
(393, 'Çat', 5, 'Mülhakat', 'Faal', NULL, 'Erzurum', 'Erzurum'),
(394, 'Horasan', 4, 'Mülhakat', 'Faal', NULL, 'Erzurum', 'Erzurum'),
(395, 'İspir', 5, 'Mülhakat', 'Faal', NULL, 'Erzurum', 'Erzurum'),
(396, 'Karayazı', 5, 'Mülhakat', 'Faal', NULL, 'Erzurum', 'Erzurum'),
(397, 'Pasinler', 3, 'Mülhakat', 'Faal', NULL, 'Erzurum', 'Erzurum'),
(398, 'Tortum', 5, 'Mülhakat', 'Faal', NULL, 'Erzurum', 'Erzurum'),
(399, 'Aziziye', NULL, NULL, 'Faal Değil', 'Erzurum', 'Erzurum', 'Erzurum'),
(400, 'Köprüköy', NULL, NULL, 'Birleştirildi', 'Pasinler', 'Erzurum', 'Erzurum'),
(401, 'Palandöken', NULL, NULL, 'Teşkilat Kurulmadı', 'Erzurum', 'Erzurum', 'Erzurum'),
(402, 'Pazaryolu', NULL, NULL, 'Birleştirildi', 'İspir', 'Erzurum', 'Erzurum'),
(403, 'Uzundere', NULL, NULL, 'Birleştirildi', 'Tortum', 'Erzurum', 'Erzurum'),
(404, 'Yakutiye', NULL, NULL, 'Teşkilat Kurulmadı', 'Erzurum', 'Erzurum', 'Erzurum'),
(405, 'Eskişehir', 1, 'ACM', 'Faal', NULL, 'Eskişehir', 'Eskişehir'),
(406, 'Beylikova', 4, 'Mülhakat', 'Faal', NULL, 'Eskişehir', 'Eskişehir'),
(407, 'Çifteler', 3, 'Mülhakat', 'Faal', NULL, 'Eskişehir', 'Eskişehir'),
(408, 'Mihalıççık', 3, 'Mülhakat', 'Faal', NULL, 'Eskişehir', 'Eskişehir'),
(409, 'Sivrihisar', 3, 'Mülhakat', 'Faal', NULL, 'Eskişehir', 'Eskişehir'),
(410, 'Alpu', NULL, NULL, 'Birleştirildi', 'Beylikova', 'Eskişehir', 'Eskişehir'),
(411, 'Günyüzü', NULL, NULL, 'Birleştirildi', 'Sivrihisar', 'Eskişehir', 'Eskişehir'),
(412, 'Han', NULL, NULL, 'Birleştirildi', 'Çifteler', 'Eskişehir', 'Eskişehir'),
(413, 'Mahmudiye', NULL, NULL, 'Birleştirildi', 'Çifteler', 'Eskişehir', 'Eskişehir'),
(414, 'Mihalgazi', NULL, NULL, 'Birleştirildi', 'Eskişehir', 'Eskişehir', 'Eskişehir'),
(415, 'Odunpazarı', NULL, NULL, 'Teşkilat Kurulmadı', 'Eskişehir', 'Eskişehir', 'Eskişehir'),
(416, 'Sarıcakaya', NULL, NULL, 'Birleştirildi', 'Eskişehir', 'Eskişehir', 'Eskişehir'),
(417, 'Seyitgazi', NULL, NULL, 'Birleştirildi', 'Eskişehir', 'Eskişehir', 'Eskişehir'),
(418, 'Tepebaşı', NULL, NULL, 'Teşkilat Kurulmadı', 'Eskişehir', 'Eskişehir', 'Eskişehir'),
(419, 'Fatsa', 2, 'ACM', 'Faal', NULL, 'Fatsa', 'Ordu'),
(420, 'Aybastı', 4, 'Mülhakat', 'Faal', NULL, 'Fatsa', 'Ordu'),
(421, 'Korgan', 4, 'Mülhakat', 'Faal', NULL, 'Fatsa', 'Ordu'),
(422, 'Kumru', 4, 'Mülhakat', 'Faal', NULL, 'Fatsa', 'Ordu'),
(423, 'Çamaş', NULL, NULL, 'Birleştirildi', 'Fatsa', 'Fatsa', 'Ordu'),
(424, 'Çatalpınar', NULL, NULL, 'Birleştirildi', 'Fatsa', 'Fatsa', 'Ordu'),
(425, 'Kabataş', NULL, NULL, 'Birleştirildi', 'Aybastı', 'Fatsa', 'Ordu'),
(426, 'Fethiye', 2, 'ACM', 'Faal', NULL, 'Fethiye', 'Muğla'),
(427, 'Ortaca', 2, 'Mülhakat', 'Faal', NULL, 'Fethiye', 'Muğla'),
(428, 'Seydikemer', 3, 'Mülhakat', 'Faal', NULL, 'Fethiye', 'Muğla'),
(429, 'Dalaman', NULL, NULL, 'Birleştirildi', 'Ortaca', 'Fethiye', 'Muğla'),
(430, 'Gaziantep', 1, 'ACM', 'Faal', NULL, 'Gaziantep', 'Gaziantep'),
(431, 'Araban', 5, 'Mülhakat', 'Faal', NULL, 'Gaziantep', 'Gaziantep'),
(432, 'Oğuzeli', NULL, NULL, 'Birleştirildi', 'Gaziantep', 'Gaziantep', 'Gaziantep'),
(433, 'Şahinbey', NULL, NULL, 'Teşkilat Kurulmadı', 'Gaziantep', 'Gaziantep', 'Gaziantep'),
(434, 'Şehitkamil', NULL, NULL, 'Teşkilat Kurulmadı', 'Gaziantep', 'Gaziantep', 'Gaziantep'),
(435, 'Yavuzeli', NULL, NULL, 'Birleştirildi', 'Gaziantep', 'Gaziantep', 'Gaziantep'),
(436, 'Gaziosmanpaşa', 1, 'ACM', 'Faal', NULL, 'Gaziosmanpaşa', 'İstanbul'),
(437, 'Arnavutköy', NULL, NULL, 'Teşkilat Kurulmadı', 'Gaziosmanpaşa', 'İstanbul', 'İstanbul'),
(438, 'Eyüpsultan', NULL, NULL, 'Birleştirildi', 'Gaziosmanpaşa', 'İstanbul', 'İstanbul'),
(439, 'Sultangazi', NULL, NULL, 'Teşkilat Kurulmadı', 'Gaziosmanpaşa', 'İstanbul', 'İstanbul'),
(440, 'Gebze', 1, 'ACM', 'Faal', NULL, 'Gebze', 'Kocaeli'),
(441, 'Çayırova', NULL, NULL, 'Teşkilat Kurulmadı', 'Gebze', 'Gebze', 'Kocaeli'),
(442, 'Darıca', NULL, NULL, 'Teşkilat Kurulmadı', 'Gebze', 'Gebze', 'Kocaeli'),
(443, 'Dilovası', NULL, NULL, 'Teşkilat Kurulmadı', 'Gebze', 'Gebze', 'Kocaeli'),
(444, 'Gemlik', 2, 'ACM', 'Faal', NULL, 'Gemlik', 'Bursa'),
(445, 'Armutlu (FD)', 3, 'Mülhakat', 'Teşkilat Kurulmadı', 'Gemlik', 'Gemlik', 'Yalova'),
(446, 'Orhangazi', 2, 'Mülhakat', 'Faal', NULL, 'Gemlik', 'Bursa'),
(447, 'Giresun', 2, 'ACM', 'Faal', NULL, 'Giresun', 'Giresun'),
(448, 'Bulancak', 2, 'Mülhakat', 'Faal', NULL, 'Giresun', 'Giresun'),
(449, 'Dereli', 4, 'Mülhakat', 'Faal', NULL, 'Giresun', 'Giresun'),
(450, 'Espiye', 3, 'Mülhakat', 'Faal', NULL, 'Giresun', 'Giresun'),
(451, 'Görele', 3, 'Mülhakat', 'Faal', NULL, 'Giresun', 'Giresun'),
(452, 'Tirebolu', 2, 'Mülhakat', 'Faal', NULL, 'Giresun', 'Giresun'),
(453, 'Çanakçı', NULL, NULL, 'Teşkilat Kurulmadı', 'Görele', 'Giresun', 'Giresun'),
(454, 'Doğankent', NULL, NULL, 'Faal Değil', 'Tirebolu', 'Giresun', 'Giresun'),
(455, 'Eynesil', NULL, NULL, 'Birleştirildi', 'Görele', 'Giresun', 'Giresun'),
(456, 'Güce', NULL, NULL, 'Faal Değil', 'Tirebolu', 'Giresun', 'Giresun'),
(457, 'Keşap', NULL, NULL, 'Birleştirildi', 'Giresun', 'Giresun', 'Giresun'),
(458, 'Piraziz', NULL, NULL, 'Birleştirildi', 'Bulancak', 'Giresun', 'Giresun'),
(459, 'Yağlıdere', NULL, NULL, 'Birleştirildi', 'Espiye', 'Giresun', 'Giresun'),
(460, 'Gümüşhane', 3, 'ACM', 'Faal', NULL, 'Gümüşhane', 'Gümüşhane'),
(461, 'Kelkit', 4, 'Mülhakat', 'Faal', NULL, 'Gümüşhane', 'Gümüşhane'),
(462, 'Şiran', 5, 'Mülhakat', 'Faal', NULL, 'Gümüşhane', 'Gümüşhane'),
(463, 'Torul', 4, 'Mülhakat', 'Faal', NULL, 'Gümüşhane', 'Gümüşhane'),
(464, 'Köse', NULL, NULL, 'Birleştirildi', 'Kelkit', 'Gümüşhane', 'Gümüşhane'),
(465, 'Kürtün', NULL, NULL, 'Birleştirildi', 'Torul', 'Gümüşhane', 'Gümüşhane'),
(466, 'Hakkâri', 3, 'ACM', 'Faal', NULL, 'Hakkâri', 'Hakkâri'),
(467, 'Çukurca', 5, 'Mülhakat', 'Faal', NULL, 'Hakkâri', 'Hakkâri'),
(468, 'Hatay', 1, 'ACM', 'Faal', NULL, 'Hatay', 'Hatay'),
(469, 'Altınözü', 4, 'Mülhakat', 'Faal', NULL, 'Hatay', 'Hatay'),
(470, 'Samandağ', 3, 'Mülhakat', 'Faal', NULL, 'Hatay', 'Hatay'),
(471, 'Yayladağı', 4, 'Mülhakat', 'Faal', NULL, 'Hatay', 'Hatay'),
(472, 'Antakya', NULL, NULL, 'Teşkilat Kurulmadı', 'Hatay', 'Hatay', 'Hatay'),
(473, 'Defne', NULL, NULL, 'Teşkilat Kurulmadı', 'Hatay', 'Hatay', 'Hatay'),
(474, 'Hınıs', 3, 'ACM', 'Faal', NULL, 'Hınıs', 'Erzurum'),
(475, 'Tekman', 5, 'Mülhakat', 'Faal', NULL, 'Hınıs', 'Erzurum'),
(476, 'Karaçoban', NULL, NULL, 'Birleştirildi', 'Hınıs', 'Hınıs', 'Erzurum'),
(477, 'Iğdır', 3, 'ACM', 'Faal', NULL, 'Iğdır', 'Iğdır'),
(478, 'Aralık', 5, 'Mülhakat', 'Faal', NULL, 'Iğdır', 'Iğdır'),
(479, 'Tuzluca', 5, 'Mülhakat', 'Faal', NULL, 'Iğdır', 'Iğdır'),
(480, 'Karakoyunlu', NULL, NULL, 'Teşkilat Kurulmadı', 'Iğdır', 'Iğdır', 'Iğdır'),
(481, 'Isparta', 1, 'ACM', 'Faal', NULL, 'Isparta', 'Isparta'),
(482, 'Eğirdir', 3, 'Mülhakat', 'Faal', NULL, 'Isparta', 'Isparta'),
(483, 'Keçiborlu', 3, 'Mülhakat', 'Faal', NULL, 'Isparta', 'Isparta'),
(484, 'Senirkent', 4, 'Mülhakat', 'Faal', NULL, 'Isparta', 'Isparta'),
(485, 'Sütçüler', 5, 'Mülhakat', 'Faal', NULL, 'Isparta', 'Isparta'),
(486, 'Aksu', NULL, NULL, 'Birleştirildi', 'Eğirdir', 'Isparta', 'Isparta'),
(487, 'Atabey', NULL, NULL, 'Birleştirildi', 'Isparta', 'Isparta', 'Isparta'),
(488, 'Gönen (Isparta)', NULL, NULL, 'Teşkilat Kurulmadı', 'Isparta', 'Isparta', 'Isparta'),
(489, 'Uluborlu', NULL, NULL, 'Birleştirildi', 'Keçiborlu', 'Isparta', 'Isparta'),
(490, 'İnebolu', 2, 'ACM', 'Faal', NULL, 'İnebolu', 'Kastamonu'),
(491, 'Küre', 4, 'Mülhakat', 'Faal', NULL, 'İnebolu', 'Kastamonu'),
(492, 'Abana', NULL, NULL, 'Birleştirildi', 'İnebolu', 'İnebolu', 'Kastamonu'),
(493, 'Ağlı', NULL, NULL, 'Birleştirildi', 'Küre', 'İnebolu', 'Kastamonu'),
(494, 'Bozkurt (İnebolu)', NULL, NULL, 'Birleştirildi', 'İnebolu', 'İnebolu', 'Kastamonu'),
(495, 'Çatalzeytin', NULL, NULL, 'Birleştirildi', 'İnebolu', 'İnebolu', 'Kastamonu'),
(496, 'Doğanyurt', NULL, NULL, 'Birleştirildi', 'İnebolu', 'İnebolu', 'Kastamonu'),
(497, 'İnegöl', 2, 'ACM', 'Faal', NULL, 'İnegöl', 'Bursa'),
(498, 'İznik', 2, 'Mülhakat', 'Faal', NULL, 'İnegöl', 'Bursa'),
(499, 'Yenişehir', 2, 'Mülhakat', 'Faal', NULL, 'İnegöl', 'Bursa'),
(500, 'İskenderun', 1, 'ACM', 'Faal', NULL, 'İskenderun', 'Hatay'),
(501, 'Arsuz', NULL, NULL, 'Teşkilat Kurulmadı', 'İskenderun', 'İskenderun', 'Hatay'),
(502, 'Belen', NULL, NULL, 'Teşkilat Kurulmadı', 'İskenderun', 'İskenderun', 'Hatay'),
(503, 'İslâhiye', 3, 'ACM', 'Faal', NULL, 'İslâhiye', 'Gaziantep'),
(504, 'Nurdağı', 4, 'Mülhakat', 'Faal', NULL, 'İslâhiye', 'Gaziantep'),
(505, 'İstanbul', 1, 'ACM', 'Faal', NULL, 'İstanbul', 'İstanbul'),
(506, 'Bayrampaşa', NULL, NULL, 'Teşkilat Kurulmadı', 'İstanbul', 'İstanbul', 'İstanbul'),
(507, 'Beşiktaş', NULL, NULL, 'Teşkilat Kurulmadı', 'İstanbul', 'İstanbul', 'İstanbul'),
(508, 'Beyoğlu', NULL, NULL, 'Birleştirildi', 'İstanbul', 'İstanbul', 'İstanbul'),
(509, 'Fatih', NULL, NULL, 'Birleştirildi', 'İstanbul', 'İstanbul', 'İstanbul'),
(510, 'Kağıthane', NULL, NULL, 'Teşkilat Kurulmadı', 'İstanbul', 'İstanbul', 'İstanbul'),
(511, 'Sarıyer', NULL, NULL, 'Birleştirildi', 'İstanbul', 'İstanbul', 'İstanbul'),
(512, 'Şişli', NULL, NULL, 'Birleştirildi', 'İstanbul', 'İstanbul', 'İstanbul'),
(513, 'İstanbul Anadolu', 1, 'ACM', 'Faal', NULL, 'İstanbul Anadolu', 'İstanbul'),
(514, 'Adalar', 1, 'Mülhakat', 'Faal', NULL, 'İstanbul Anadolu', 'İstanbul'),
(515, 'Beykoz', 1, 'Mülhakat', 'Faal', NULL, 'İstanbul Anadolu', 'İstanbul'),
(516, 'Şile', 2, 'Mülhakat', 'Faal', NULL, 'İstanbul Anadolu', 'İstanbul'),
(517, 'Ataşehir', NULL, NULL, 'Teşkilat Kurulmadı', 'İstanbul Anadolu', 'İstanbul Anadolu', 'İstanbul'),
(518, 'Çekmeköy', NULL, NULL, 'Teşkilat Kurulmadı', 'İstanbul Anadolu', 'İstanbul Anadolu', 'İstanbul'),
(519, 'Kadıköy', NULL, NULL, 'Birleştirildi', 'İstanbul Anadolu', 'İstanbul Anadolu', 'İstanbul'),
(520, 'Kartal', NULL, NULL, 'Birleştirildi', 'İstanbul Anadolu', 'İstanbul Anadolu', 'İstanbul'),
(521, 'Maltepe', NULL, NULL, 'Teşkilat Kurulmadı', 'İstanbul Anadolu', 'İstanbul Anadolu', 'İstanbul'),
(522, 'Pendik', NULL, NULL, 'Birleştirildi', 'İstanbul Anadolu', 'İstanbul Anadolu', 'İstanbul'),
(523, 'Sancaktepe', NULL, NULL, 'Teşkilat Kurulmadı', 'İstanbul Anadolu', 'İstanbul Anadolu', 'İstanbul'),
(524, 'Sultanbeyli', NULL, NULL, 'Birleştirildi', 'İstanbul Anadolu', 'İstanbul Anadolu', 'İstanbul'),
(525, 'Tuzla', NULL, NULL, 'Birleştirildi', 'İstanbul Anadolu', 'İstanbul Anadolu', 'İstanbul'),
(526, 'Ümraniye', NULL, NULL, 'Birleştirildi', 'İstanbul Anadolu', 'İstanbul Anadolu', 'İstanbul'),
(527, 'Üsküdar', NULL, NULL, 'Birleştirildi', 'İstanbul Anadolu', 'İstanbul Anadolu', 'İstanbul'),
(528, 'İzmir', 1, 'ACM', 'Faal', NULL, 'İzmir', 'İzmir'),
(529, 'Kemalpaşa', 2, 'Mülhakat', 'Faal', NULL, 'İzmir', 'İzmir'),
(530, 'Menderes', 1, 'Mülhakat', 'Faal', NULL, 'İzmir', 'İzmir'),
(531, 'Seferihisar', 2, 'Mülhakat', 'Faal', NULL, 'İzmir', 'İzmir'),
(532, 'Urla', 2, 'Mülhakat', 'Faal', NULL, 'İzmir', 'İzmir'),
(533, 'Balçova', NULL, NULL, 'Teşkilat Kurulmadı', 'İzmir', 'İzmir', 'İzmir'),
(534, 'Bayraklı', NULL, NULL, 'Teşkilat Kurulmadı', 'İzmir', 'İzmir', 'İzmir'),
(535, 'Bornova', NULL, NULL, 'Birleştirildi', 'İzmir', 'İzmir', 'İzmir'),
(536, 'Buca', NULL, NULL, 'Teşkilat Kurulmadı', 'İzmir', 'İzmir', 'İzmir'),
(537, 'Gaziemir', NULL, NULL, 'Teşkilat Kurulmadı', 'İzmir', 'İzmir', 'İzmir'),
(538, 'Güzelbahçe', NULL, NULL, 'Teşkilat Kurulmadı', 'İzmir', 'İzmir', 'İzmir'),
(539, 'Karabağlar', NULL, NULL, 'Teşkilat Kurulmadı', 'İzmir', 'İzmir', 'İzmir'),
(540, 'Konak', NULL, NULL, 'Teşkilat Kurulmadı', 'İzmir', 'İzmir', 'İzmir'),
(541, 'Narlıdere', NULL, NULL, 'Teşkilat Kurulmadı', 'İzmir', 'İzmir', 'İzmir'),
(542, 'Kadirli', 3, 'ACM', 'Faal', NULL, 'Kadirli', 'Osmaniye'),
(543, 'Sumbas', NULL, NULL, 'Teşkilat Kurulmadı', 'Kadirli', 'Kadirli', 'Osmaniye'),
(544, 'Kahramanmaraş', 1, 'ACM', 'Faal', NULL, 'Kahramanmaraş', 'Kahramanmaraş'),
(545, 'Andırın', 4, 'Mülhakat', 'Faal', NULL, 'Kahramanmaraş', 'Kahramanmaraş'),
(546, 'Göksun', 4, 'Mülhakat', 'Faal', NULL, 'Kahramanmaraş', 'Kahramanmaraş'),
(547, 'Pazarcık', 3, 'Mülhakat', 'Faal', NULL, 'Kahramanmaraş', 'Kahramanmaraş'),
(548, 'Türkoğlu', 3, 'Mülhakat', 'Faal', NULL, 'Kahramanmaraş', 'Kahramanmaraş'),
(549, 'Çağlayancerit', NULL, NULL, 'Birleştirildi', 'Pazarcık', 'Kahramanmaraş', 'Kahramanmaraş'),
(550, 'Dulkadiroğlu', NULL, NULL, 'Teşkilat Kurulmadı', 'Kahramanmaraş', 'Kahramanmaraş', 'Kahramanmaraş'),
(551, 'Onikişubat', NULL, NULL, 'Teşkilat Kurulmadı', 'Kahramanmaraş', 'Kahramanmaraş', 'Kahramanmaraş'),
(552, 'Karabük', 2, 'ACM', 'Faal', NULL, 'Karabük', 'Karabük'),
(553, 'Çerkeş', 3, 'Mülhakat', 'Faal', NULL, 'Karabük', 'Çankırı'),
(554, 'Eskipazar', 4, 'Mülhakat', 'Faal', NULL, 'Karabük', 'Karabük'),
(555, 'Safranbolu', 2, 'Mülhakat', 'Faal', NULL, 'Karabük', 'Karabük'),
(556, 'Yenice (Karabük)', 4, 'Mülhakat', 'Faal', NULL, 'Karabük', 'Karabük'),
(557, 'Eflâni', NULL, NULL, 'Birleştirildi', 'Safranbolu', 'Karabük', 'Karabük'),
(558, 'Ovacık (Karabük)', NULL, NULL, 'Birleştirildi', 'Karabük', 'Karabük', 'Karabük'),
(559, 'Karaman', 2, 'ACM', 'Faal', NULL, 'Karaman', 'Karaman'),
(560, 'Ayrancı', NULL, NULL, 'Birleştirildi', 'Karaman', 'Karaman', 'Karaman'),
(561, 'Kazımkarabekir', NULL, NULL, 'Birleştirildi', 'Karaman', 'Karaman', 'Karaman'),
(562, 'Kars', 2, 'ACM', 'Faal', NULL, 'Kars', 'Kars'),
(563, 'Arpaçay', 5, 'Mülhakat', 'Faal', NULL, 'Kars', 'Kars'),
(564, 'Digor', 5, 'Mülhakat', 'Faal', NULL, 'Kars', 'Kars'),
(565, 'Kağızman', 4, 'Mülhakat', 'Faal', NULL, 'Kars', 'Kars'),
(566, 'Sarıkamış', 3, 'Mülhakat', 'Faal', NULL, 'Kars', 'Kars'),
(567, 'Selim', 5, 'Mülhakat', 'Faal', NULL, 'Kars', 'Kars'),
(568, 'Akyaka', NULL, NULL, 'Birleştirildi', 'Kars', 'Kars', 'Kars'),
(569, 'Susuz', NULL, NULL, 'Birleştirildi', 'Kars', 'Kars', 'Kars'),
(570, 'Karşıyaka', 1, 'ACM', 'Faal', NULL, 'Karşıyaka', 'İzmir'),
(571, 'Çiğli', NULL, NULL, 'Teşkilat Kurulmadı', 'Karşıyaka', 'Karşıyaka', 'İzmir'),
(572, 'Kastamonu', 2, 'ACM', 'Faal', NULL, 'Kastamonu', 'Kastamonu'),
(573, 'Araç', 4, 'Mülhakat', 'Faal', NULL, 'Kastamonu', 'Kastamonu'),
(574, 'Azdavay', 4, 'Mülhakat', 'Faal', NULL, 'Kastamonu', 'Kastamonu'),
(575, 'Cide', 4, 'Mülhakat', 'Faal', NULL, 'Kastamonu', 'Kastamonu'),
(576, 'Devrekâni', 4, 'Mülhakat', 'Faal', NULL, 'Kastamonu', 'Kastamonu'),
(577, 'Taşköprü', 3, 'Mülhakat', 'Faal', NULL, 'Kastamonu', 'Kastamonu'),
(578, 'Tosya', 3, 'Mülhakat', 'Faal', NULL, 'Kastamonu', 'Kastamonu'),
(579, 'Daday', NULL, NULL, 'Birleştirildi', 'Kastamonu', 'Kastamonu', 'Kastamonu'),
(580, 'Hanönü', NULL, NULL, 'Birleştirildi', 'Taşköprü', 'Kastamonu', 'Kastamonu'),
(581, 'İhsangazi', NULL, NULL, 'Birleştirildi', 'Kastamonu', 'Kastamonu', 'Kastamonu'),
(582, 'Pınarbaşı (Kastamonu)', NULL, NULL, 'Birleştirildi', 'Azdavay', 'Kastamonu', 'Kastamonu'),
(583, 'Seydiler', NULL, NULL, 'Birleştirildi', 'Devrekâni', 'Kastamonu', 'Kastamonu'),
(584, 'Şenpazar', NULL, NULL, 'Birleştirildi', 'Cide', 'Kastamonu', 'Kastamonu'),
(585, 'Kayseri', 1, 'ACM', 'Faal', NULL, 'Kayseri', 'Kayseri'),
(586, 'Bünyan', 3, 'Mülhakat', 'Faal', NULL, 'Kayseri', 'Kayseri'),
(587, 'İncesu', 3, 'Mülhakat', 'Faal', NULL, 'Kayseri', 'Kayseri'),
(588, 'Pınarbaşı', 4, 'Mülhakat', 'Faal', NULL, 'Kayseri', 'Kayseri'),
(589, 'Sarıoğlan', 4, 'Mülhakat', 'Faal', NULL, 'Kayseri', 'Kayseri'),
(590, 'Sarız', 4, 'Mülhakat', 'Faal', NULL, 'Kayseri', 'Kayseri'),
(591, 'Akkışla', NULL, NULL, 'Birleştirildi', 'Sarıoğlan', 'Kayseri', 'Kayseri'),
(592, 'Felâhiye', NULL, NULL, 'Birleştirildi', 'Kayseri', 'Kayseri', 'Kayseri'),
(593, 'Hacılar', NULL, NULL, 'Teşkilat Kurulmadı', 'Kayseri', 'Kayseri', 'Kayseri'),
(594, 'Kocasinan', NULL, NULL, 'Teşkilat Kurulmadı', 'Kayseri', 'Kayseri', 'Kayseri'),
(595, 'Melikgazi', NULL, NULL, 'Teşkilat Kurulmadı', 'Kayseri', 'Kayseri', 'Kayseri'),
(596, 'Özvatan', NULL, NULL, 'Birleştirildi', 'Felâhiye', 'Kayseri', 'Kayseri'),
(597, 'Talas', NULL, NULL, 'Teşkilat Kurulmadı', 'Kayseri', 'Kayseri', 'Kayseri'),
(598, 'Keşan', 2, 'ACM', 'Faal', NULL, 'Keşan', 'Edirne'),
(599, 'Enez', 4, 'Mülhakat', 'Faal', NULL, 'Keşan', 'Edirne'),
(600, 'İpsala', 3, 'Mülhakat', 'Faal', NULL, 'Keşan', 'Edirne'),
(601, 'Kırıkhan', 3, 'ACM', 'Faal', NULL, 'Kırıkhan', 'Hatay'),
(602, 'Hassa', 4, 'Mülhakat', 'Faal', NULL, 'Kırıkhan', 'Hatay'),
(603, 'Kırıkkale', 1, 'ACM', 'Faal', NULL, 'Kırıkkale', 'Kırıkkale'),
(604, 'Delice', 4, 'Mülhakat', 'Faal', NULL, 'Kırıkkale', 'Kırıkkale'),
(605, 'Keskin', 3, 'Mülhakat', 'Faal', NULL, 'Kırıkkale', 'Kırıkkale'),
(606, 'Sulakyurt', 4, 'Mülhakat', 'Faal', NULL, 'Kırıkkale', 'Kırıkkale'),
(607, 'Bahşılı', NULL, NULL, 'Teşkilat Kurulmadı', 'Kırıkkale', 'Kırıkkale', 'Kırıkkale'),
(608, 'Balışeyh', NULL, NULL, 'Teşkilat Kurulmadı', 'Kırıkkale', 'Kırıkkale', 'Kırıkkale'),
(609, 'Çelebi', NULL, NULL, 'Teşkilat Kurulmadı', 'Keskin', 'Kırıkkale', 'Kırıkkale'),
(610, 'Karakeçili', NULL, NULL, 'Birleştirildi', 'Kırıkkale', 'Kırıkkale', 'Kırıkkale'),
(611, 'Yahşihan', NULL, NULL, 'Teşkilat Kurulmadı', 'Kırıkkale', 'Kırıkkale', 'Kırıkkale'),
(612, 'Kırklareli', 2, 'ACM', 'Faal', NULL, 'Kırklareli', 'Kırklareli'),
(613, 'Babaeski', 2, 'Mülhakat', 'Faal', NULL, 'Kırklareli', 'Kırklareli'),
(614, 'Demirköy', 4, 'Mülhakat', 'Faal', NULL, 'Kırklareli', 'Kırklareli'),
(615, 'Kofçaz', NULL, NULL, 'Birleştirildi', 'Kırklareli', 'Kırklareli', 'Kırklareli'),
(616, 'Pehlivanköy', NULL, NULL, 'Birleştirildi', 'Babaeski', 'Kırklareli', 'Kırklareli'),
(617, 'Kırşehir', 1, 'ACM', 'Faal', NULL, 'Kırşehir', 'Kırşehir'),
(618, 'Kaman', 3, 'Mülhakat', 'Faal', NULL, 'Kırşehir', 'Kırşehir'),
(619, 'Mucur', 3, 'Mülhakat', 'Faal', NULL, 'Kırşehir', 'Kırşehir'),
(620, 'Akpınar', NULL, NULL, 'Birleştirildi', 'Kırşehir', 'Kırşehir', 'Kırşehir'),
(621, 'Boztepe', NULL, NULL, 'Birleştirildi', 'Kırşehir', 'Kırşehir', 'Kırşehir'),
(622, 'Kilis', 2, 'ACM', 'Faal', NULL, 'Kilis', 'Kilis'),
(623, 'Elbeyli', NULL, NULL, 'Teşkilat Kurulmadı', 'Kilis', 'Kilis', 'Kilis'),
(624, 'Musabeyli', NULL, NULL, 'Teşkilat Kurulmadı', 'Kilis', 'Kilis', 'Kilis'),
(625, 'Polateli', NULL, NULL, 'Teşkilat Kurulmadı', 'Kilis', 'Kilis', 'Kilis'),
(626, 'Kocaeli', 1, 'ACM', 'Faal', NULL, 'Kocaeli', 'Kocaeli'),
(627, 'Gölcük', 2, 'Mülhakat', 'Faal', NULL, 'Kocaeli', 'Kocaeli'),
(628, 'Kandıra', 3, 'Mülhakat', 'Faal', NULL, 'Kocaeli', 'Kocaeli'),
(629, 'Karamürsel', 2, 'Mülhakat', 'Faal', NULL, 'Kocaeli', 'Kocaeli'),
(630, 'Körfez', 2, 'Mülhakat', 'Faal', NULL, 'Kocaeli', 'Kocaeli'),
(631, 'Başiskele', NULL, NULL, 'Teşkilat Kurulmadı', 'Kocaeli', 'Kocaeli', 'Kocaeli'),
(632, 'Derince', NULL, NULL, 'Teşkilat Kurulmadı', 'Kocaeli', 'Kocaeli', 'Kocaeli'),
(633, 'İzmit', NULL, NULL, 'Teşkilat Kurulmadı', 'Kocaeli', 'Kocaeli', 'Kocaeli'),
(634, 'Kartepe', NULL, NULL, 'Teşkilat Kurulmadı', 'Kocaeli', 'Kocaeli', 'Kocaeli'),
(635, 'Konya', 1, 'ACM', 'Faal', NULL, 'Konya', 'Konya'),
(636, 'Cihanbeyli', 3, 'Mülhakat', 'Faal', NULL, 'Konya', 'Konya'),
(637, 'Çumra', 3, 'Mülhakat', 'Faal', NULL, 'Konya', 'Konya'),
(638, 'Hadim', 4, 'Mülhakat', 'Faal', NULL, 'Konya', 'Konya'),
(639, 'Kadınhanı', 3, 'Mülhakat', 'Faal', NULL, 'Konya', 'Konya'),
(640, 'Kulu', 3, 'Mülhakat', 'Faal', NULL, 'Konya', 'Konya'),
(641, 'Sarayönü', 3, 'Mülhakat', 'Faal', NULL, 'Konya', 'Konya'),
(642, 'Akören', NULL, NULL, 'Birleştirildi', 'Konya', 'Konya', 'Konya'),
(643, 'Altınekin', NULL, NULL, 'Birleştirildi', 'Konya', 'Konya', 'Konya'),
(644, 'Derbent', NULL, NULL, 'Teşkilat Kurulmadı', 'Konya', 'Konya', 'Konya'),
(645, 'Güneysınır', NULL, NULL, 'Birleştirildi', 'Çumra', 'Konya', 'Konya'),
(646, 'Karatay', NULL, NULL, 'Teşkilat Kurulmadı', 'Konya', 'Konya', 'Konya'),
(647, 'Meram', NULL, NULL, 'Teşkilat Kurulmadı', 'Konya', 'Konya', 'Konya'),
(648, 'Selçuklu', NULL, NULL, 'Teşkilat Kurulmadı', 'Konya', 'Konya', 'Konya'),
(649, 'Taşkent', NULL, NULL, 'Birleştirildi', 'Hadim', 'Konya', 'Konya'),
(650, 'Kozan', 2, 'ACM', 'Faal', NULL, 'Kozan', 'Adana'),
(651, 'Aladağ', 5, 'Mülhakat', 'Faal', NULL, 'Kozan', 'Adana'),
(652, 'Feke', 4, 'Mülhakat', 'Faal', NULL, 'Kozan', 'Adana'),
(653, 'İmamoğlu', 3, 'Mülhakat', 'Faal', NULL, 'Kozan', 'Adana'),
(654, 'Tufanbeyli', 5, 'Mülhakat', 'Faal', NULL, 'Kozan', 'Adana'),
(655, 'Saimbeyli', NULL, NULL, 'Birleştirildi', 'Feke', 'Kozan', 'Adana'),
(656, 'Küçükçekmece', 1, 'ACM', 'Faal', NULL, 'Küçükçekmece', 'İstanbul'),
(657, 'Avcılar', NULL, NULL, 'Teşkilat Kurulmadı', 'Küçükçekmece', 'Küçükçekmece', 'İstanbul'),
(658, 'Başakşehir', NULL, NULL, 'Teşkilat Kurulmadı', 'Küçükçekmece', 'Küçükçekmece', 'İstanbul'),
(659, 'Kütahya', 1, 'ACM', 'Faal', NULL, 'Kütahya', 'Kütahya'),
(660, 'Altıntaş', 4, 'Mülhakat', 'Faal', NULL, 'Kütahya', 'Kütahya'),
(661, 'Gediz', 3, 'Mülhakat', 'Faal', NULL, 'Kütahya', 'Kütahya'),
(662, 'Aslanapa', NULL, NULL, 'Birleştirildi', 'Kütahya', 'Kütahya', 'Kütahya'),
(663, 'Çavdarhisar', NULL, NULL, 'Birleştirildi', 'Gediz', 'Kütahya', 'Kütahya'),
(664, 'Dumlupınar', NULL, NULL, 'Birleştirildi', 'Altıntaş', 'Kütahya', 'Kütahya'),
(665, 'Şaphane', NULL, NULL, 'Birleştirildi', 'Gediz', 'Kütahya', 'Kütahya'),
(666, 'Lüleburgaz', 2, 'ACM', 'Faal', NULL, 'Lüleburgaz', 'Kırklareli'),
(667, 'Pınarhisar', 3, 'Mülhakat', 'Faal', NULL, 'Lüleburgaz', 'Kırklareli'),
(668, 'Vize', 3, 'Mülhakat', 'Faal', NULL, 'Lüleburgaz', 'Kırklareli'),
(669, 'Malatya', 1, 'ACM', 'Faal', NULL, 'Malatya', 'Malatya'),
(670, 'Akçadağ', 4, 'Mülhakat', 'Faal', NULL, 'Malatya', 'Malatya'),
(671, 'Arapgir', 4, 'Mülhakat', 'Faal', NULL, 'Malatya', 'Malatya'),
(672, 'Darende', 4, 'Mülhakat', 'Faal', NULL, 'Malatya', 'Malatya'),
(673, 'Doğanşehir', 4, 'Mülhakat', 'Faal', NULL, 'Malatya', 'Malatya'),
(674, 'Hekimhan', 4, 'Mülhakat', 'Faal', NULL, 'Malatya', 'Malatya'),
(675, 'Pütürge', 4, 'Mülhakat', 'Faal', NULL, 'Malatya', 'Malatya'),
(676, 'Arguvan', NULL, NULL, 'Birleştirildi', 'Malatya', 'Malatya', 'Malatya'),
(677, 'Battalgazi', NULL, NULL, 'Birleştirildi', 'Malatya', 'Malatya', 'Malatya'),
(678, 'Doğanyol', NULL, NULL, 'Birleştirildi', 'Pütürge', 'Malatya', 'Malatya'),
(679, 'Kale (Malatya)', NULL, NULL, 'Birleştirildi', 'Malatya', 'Malatya', 'Malatya'),
(680, 'Kuluncak', NULL, NULL, 'Birleştirildi', 'Hekimhan', 'Malatya', 'Malatya'),
(681, 'Yazıhan', NULL, NULL, 'Birleştirildi', 'Malatya', 'Malatya', 'Malatya'),
(682, 'Yeşilyurt (Malatya)', NULL, NULL, 'Birleştirildi', 'Malatya', 'Malatya', 'Malatya'),
(683, 'Manavgat', 1, 'ACM', 'Faal', NULL, 'Manavgat', 'Antalya'),
(684, 'Akseki', 3, 'Mülhakat', 'Faal', NULL, 'Manavgat', 'Antalya'),
(685, 'Gündoğmuş', 4, 'Mülhakat', 'Faal', NULL, 'Manavgat', 'Antalya'),
(686, 'Serik', 2, 'Mülhakat', 'Faal', NULL, 'Manavgat', 'Antalya'),
(687, 'İbradı', NULL, NULL, 'Birleştirildi', 'Akseki', 'Manavgat', 'Antalya'),
(688, 'Manisa', 1, 'ACM', 'Faal', NULL, 'Manisa', 'Manisa'),
(689, 'Saruhanlı', 3, 'Mülhakat', 'Faal', NULL, 'Manisa', 'Manisa'),
(690, 'Şehzadeler', NULL, NULL, 'Teşkilat Kurulmadı', 'Manisa', 'Manisa', 'Manisa'),
(691, 'Yunusemre', NULL, NULL, 'Teşkilat Kurulmadı', 'Manisa', 'Manisa', 'Manisa'),
(692, 'Mardin', 1, 'ACM', 'Faal', NULL, 'Mardin', 'Mardin'),
(693, 'Derik', 5, 'Mülhakat', 'Faal', NULL, 'Mardin', 'Mardin'),
(694, 'Kızıltepe', 3, 'Mülhakat', 'Faal', NULL, 'Mardin', 'Mardin'),
(695, 'Mazıdağı', 5, 'Mülhakat', 'Faal', NULL, 'Mardin', 'Mardin'),
(696, 'Nusaybin', 3, 'Mülhakat', 'Faal', NULL, 'Mardin', 'Mardin'),
(697, 'Ömerli', 5, 'Mülhakat', 'Faal', NULL, 'Mardin', 'Mardin'),
(698, 'Savur', 5, 'Mülhakat', 'Faal', NULL, 'Mardin', 'Mardin'),
(699, 'Artuklu', NULL, NULL, 'Teşkilat Kurulmadı', 'Mardin', 'Mardin', 'Mardin'),
(700, 'Yeşilli', NULL, NULL, 'Faal Değil', 'Mardin', 'Mardin', 'Mardin'),
(701, 'Menemen', 2, 'ACM', 'Faal', NULL, 'Menemen', 'İzmir'),
(702, 'Aliağa', 2, 'Mülhakat', 'Faal', NULL, 'Menemen', 'İzmir'),
(703, 'Foça', 2, 'Mülhakat', 'Faal', NULL, 'Menemen', 'İzmir'),
(704, 'Mersin', 1, 'ACM', 'Faal', NULL, 'Mersin', 'Mersin'),
(705, 'Erdemli', 2, 'Mülhakat', 'Faal', NULL, 'Mersin', 'Mersin'),
(706, 'Akdeniz', NULL, NULL, 'Teşkilat Kurulmadı', 'Mersin', 'Mersin', 'Mersin'),
(707, 'Mezitli', NULL, NULL, 'Teşkilat Kurulmadı', 'Mersin', 'Mersin', 'Mersin'),
(708, 'Toroslar', NULL, NULL, 'Teşkilat Kurulmadı', 'Mersin', 'Mersin', 'Mersin'),
(709, 'Yenişehir (Mersin)', NULL, NULL, 'Teşkilat Kurulmadı', 'Mersin', 'Mersin', 'Mersin'),
(710, 'Midyat', 3, 'ACM', 'Faal', NULL, 'Midyat', 'Mardin'),
(711, 'Dargeçit', 5, 'Mülhakat', 'Faal', NULL, 'Midyat', 'Mardin'),
(712, 'Gercüş', 5, 'Mülhakat', 'Faal', NULL, 'Midyat', 'Batman'),
(713, 'Milâs', 2, 'ACM', 'Faal', NULL, 'Milâs', 'Muğla'),
(714, 'Muğla', 1, 'ACM', 'Faal', NULL, 'Muğla', 'Muğla'),
(715, 'Datça', 3, 'Mülhakat', 'Faal', NULL, 'Muğla', 'Muğla'),
(716, 'Köyceğiz', 3, 'Mülhakat', 'Faal', NULL, 'Muğla', 'Muğla'),
(717, 'Marmaris', 2, 'Mülhakat', 'Faal', NULL, 'Muğla', 'Muğla'),
(718, 'Yatağan', 3, 'Mülhakat', 'Faal', NULL, 'Muğla', 'Muğla'),
(719, 'Kavaklıdere', NULL, NULL, 'Birleştirildi', 'Yatağan', 'Muğla', 'Muğla'),
(720, 'Menteşe', NULL, NULL, 'Teşkilat Kurulmadı', 'Muğla', 'Muğla', 'Muğla'),
(721, 'Ula', NULL, NULL, 'Birleştirildi', 'Muğla', 'Muğla', 'Muğla'),
(722, 'Mustafakemalpaşa', 2, 'ACM', 'Faal', NULL, 'Mustafakemalpaşa', 'Bursa'),
(723, 'Karacabey', 2, 'Mülhakat', 'Faal', NULL, 'Mustafakemalpaşa', 'Bursa'),
(724, 'Muş', 3, 'ACM', 'Faal', NULL, 'Muş', 'Muş'),
(725, 'Varto', 5, 'Mülhakat', 'Faal', NULL, 'Muş', 'Muş'),
(726, 'Hasköy', NULL, NULL, 'Birleştirildi', 'Muş', 'Muş', 'Muş'),
(727, 'Korkut', NULL, NULL, 'Birleştirildi', 'Muş', 'Muş', 'Muş'),
(728, 'Nazilli', 2, 'ACM', 'Faal', NULL, 'Nazilli', 'Aydın'),
(729, 'Bozdoğan', 3, 'Mülhakat', 'Faal', NULL, 'Nazilli', 'Aydın'),
(730, 'Karacasu', 4, 'Mülhakat', 'Faal', NULL, 'Nazilli', 'Aydın'),
(731, 'Buharkent', NULL, NULL, 'Birleştirildi', 'Nazilli', 'Nazilli', 'Aydın'),
(732, 'Kuyucak', NULL, NULL, 'Birleştirildi', 'Nazilli', 'Nazilli', 'Aydın'),
(733, 'Sultanhisar', NULL, NULL, 'Birleştirildi', 'Nazilli', 'Nazilli', 'Aydın'),
(734, 'Yenipazar (Aydın)', NULL, NULL, 'Birleştirildi', 'Nazilli', 'Nazilli', 'Aydın'),
(735, 'Nevşehir', 2, 'ACM', 'Faal', NULL, 'Nevşehir', 'Nevşehir'),
(736, 'Avanos', 3, 'Mülhakat', 'Faal', NULL, 'Nevşehir', 'Nevşehir'),
(737, 'Derinkuyu', 4, 'Mülhakat', 'Faal', NULL, 'Nevşehir', 'Nevşehir'),
(738, 'Gülşehir', 3, 'Mülhakat', 'Faal', NULL, 'Nevşehir', 'Nevşehir'),
(739, 'Hacıbektaş', 3, 'Mülhakat', 'Faal', NULL, 'Nevşehir', 'Nevşehir'),
(740, 'Kozaklı', 4, 'Mülhakat', 'Faal', NULL, 'Nevşehir', 'Nevşehir'),
(741, 'Ürgüp', 3, 'Mülhakat', 'Faal', NULL, 'Nevşehir', 'Nevşehir'),
(742, 'Acıgöl', NULL, NULL, 'Birleştirildi', 'Nevşehir', 'Nevşehir', 'Nevşehir'),
(743, 'Niğde', 2, 'ACM', 'Faal', NULL, 'Niğde', 'Niğde'),
(744, 'Bor', 3, 'Mülhakat', 'Faal', NULL, 'Niğde', 'Niğde'),
(745, 'Çamardı', 4, 'Mülhakat', 'Faal', NULL, 'Niğde', 'Niğde'),
(746, 'Çiftlik', 5, 'Mülhakat', 'Faal', NULL, 'Niğde', 'Niğde'),
(747, 'Ulukışla', 3, 'Mülhakat', 'Faal', NULL, 'Niğde', 'Niğde'),
(748, 'Altunhisar', NULL, NULL, 'Birleştirildi', 'Bor', 'Niğde', 'Niğde'),
(749, 'Nizip', 3, 'ACM', 'Faal', NULL, 'Nizip', 'Gaziantep'),
(750, 'Karkamış', NULL, NULL, 'Teşkilat Kurulmadı', 'Nizip', 'Nizip', 'Gaziantep'),
(751, 'Oltu', 3, 'ACM', 'Faal', NULL, 'Oltu', 'Erzurum'),
(752, 'Şenkaya', 5, 'Mülhakat', 'Faal', NULL, 'Oltu', 'Erzurum'),
(753, 'Narman', NULL, NULL, 'Birleştirildi', 'Oltu', 'Oltu', 'Erzurum'),
(754, 'Olur', NULL, NULL, 'Birleştirildi', 'Oltu', 'Oltu', 'Erzurum'),
(755, 'Ordu', 1, 'ACM', 'Faal', NULL, 'Ordu', 'Ordu'),
(756, 'Gölköy', 4, 'Mülhakat', 'Faal', NULL, 'Ordu', 'Ordu'),
(757, 'Gürgentepe', 4, 'Mülhakat', 'Faal', NULL, 'Ordu', 'Ordu'),
(758, 'Mesudiye', 5, 'Mülhakat', 'Faal', NULL, 'Ordu', 'Ordu'),
(759, 'Perşembe', 3, 'Mülhakat', 'Faal', NULL, 'Ordu', 'Ordu'),
(760, 'Altınordu', NULL, NULL, 'Teşkilat Kurulmadı', 'Ordu', 'Ordu', 'Ordu'),
(761, 'Gülyalı', NULL, NULL, 'Birleştirildi', 'Ordu', 'Ordu', 'Ordu'),
(762, 'Kabadüz', NULL, NULL, 'Birleştirildi', 'Ordu', 'Ordu', 'Ordu'),
(763, 'Ulubey (Ordu)', NULL, NULL, 'Birleştirildi', 'Ordu', 'Ordu', 'Ordu'),
(764, 'Osmaniye', 2, 'ACM', 'Faal', NULL, 'Osmaniye', 'Osmaniye'),
(765, 'Bahçe', 4, 'Mülhakat', 'Faal', NULL, 'Osmaniye', 'Osmaniye'),
(766, 'Düziçi', 3, 'Mülhakat', 'Faal', NULL, 'Osmaniye', 'Osmaniye'),
(767, 'Hasanbeyli', NULL, NULL, 'Teşkilat Kurulmadı', 'Osmaniye', 'Osmaniye', 'Osmaniye'),
(768, 'Toprakkale', NULL, NULL, 'Teşkilat Kurulmadı', 'Osmaniye', 'Osmaniye', 'Osmaniye'),
(769, 'Ödemiş', 2, 'ACM', 'Faal', NULL, 'Ödemiş', 'İzmir'),
(770, 'Bayındır', 2, 'Mülhakat', 'Faal', NULL, 'Ödemiş', 'İzmir'),
(771, 'Kiraz', 3, 'Mülhakat', 'Faal', NULL, 'Ödemiş', 'İzmir'),
(772, 'Tire', 2, 'Mülhakat', 'Faal', NULL, 'Ödemiş', 'İzmir'),
(773, 'Beydağ', NULL, NULL, 'Birleştirildi', 'Ödemiş', 'Ödemiş', 'İzmir'),
(774, 'Patnos', 3, 'ACM', 'Faal', NULL, 'Patnos', 'Ağrı'),
(775, 'Bulanık', 4, 'Mülhakat', 'Faal', NULL, 'Patnos', 'Muş'),
(776, 'Malazgirt', 4, 'Mülhakat', 'Faal', NULL, 'Patnos', 'Muş'),
(777, 'Tutak', 5, 'Mülhakat', 'Faal', NULL, 'Patnos', 'Ağrı'),
(778, 'Polatlı', 2, 'ACM', 'Faal', NULL, 'Polatlı', 'Ankara'),
(779, 'Reyhanlı', 3, 'ACM', 'Faal', NULL, 'Reyhanlı', 'Hatay'),
(780, 'Kumlu', NULL, NULL, 'Birleştirildi', 'Reyhanlı', 'Reyhanlı', 'Hatay'),
(781, 'Rize', 1, 'ACM', 'Faal', NULL, 'Rize', 'Rize'),
(782, 'Çayeli', 2, 'Mülhakat', 'Faal', NULL, 'Rize', 'Rize'),
(783, 'Kalkandere', 4, 'Mülhakat', 'Faal', NULL, 'Rize', 'Rize'),
(784, 'Pazar', 3, 'Mülhakat', 'Faal', NULL, 'Rize', 'Rize'),
(785, 'Ardeşen', NULL, NULL, 'Birleştirildi', 'Pazar', 'Rize', 'Rize'),
(786, 'Çamlıhemşin', NULL, NULL, 'Birleştirildi', 'Pazar', 'Rize', 'Rize'),
(787, 'Derepazarı', NULL, NULL, 'Teşkilat Kurulmadı', 'Rize', 'Rize', 'Rize'),
(788, 'Fındıklı', NULL, NULL, 'Birleştirildi', 'Pazar', 'Rize', 'Rize'),
(789, 'Güneysu', NULL, NULL, 'Birleştirildi', 'Rize', 'Rize', 'Rize'),
(790, 'Hemşin', NULL, NULL, 'Teşkilat Kurulmadı', 'Pazar', 'Rize', 'Rize'),
(791, 'İkizdere', NULL, NULL, 'Birleştirildi', 'Kalkandere', 'Rize', 'Rize'),
(792, 'İyidere', NULL, NULL, 'Birleştirildi', 'Rize', 'Rize', 'Rize'),
(793, 'Sakarya', 1, 'ACM', 'Faal', NULL, 'Sakarya', 'Sakarya'),
(794, 'Akyazı', 3, 'Mülhakat', 'Faal', NULL, 'Sakarya', 'Sakarya'),
(795, 'Ferizli', 3, 'Mülhakat', 'Faal', NULL, 'Sakarya', 'Sakarya'),
(796, 'Geyve', 3, 'Mülhakat', 'Faal', NULL, 'Sakarya', 'Sakarya'),
(797, 'Hendek', 2, 'Mülhakat', 'Faal', NULL, 'Sakarya', 'Sakarya'),
(798, 'Karasu', 3, 'Mülhakat', 'Faal', NULL, 'Sakarya', 'Sakarya'),
(799, 'Kaynarca', 3, 'Mülhakat', 'Faal', NULL, 'Sakarya', 'Sakarya'),
(800, 'Kocaali', 4, 'Mülhakat', 'Faal', NULL, 'Sakarya', 'Sakarya'),
(801, 'Pamukova', 3, 'Mülhakat', 'Faal', NULL, 'Sakarya', 'Sakarya'),
(802, 'Sapanca', 2, 'Mülhakat', 'Faal', NULL, 'Sakarya', 'Sakarya'),
(803, 'Adapazarı', NULL, NULL, 'Teşkilat Kurulmadı', 'Sakarya', 'Sakarya', 'Sakarya'),
(804, 'Arifiye', NULL, NULL, 'Teşkilat Kurulmadı', 'Sakarya', 'Sakarya', 'Sakarya'),
(805, 'Erenler', NULL, NULL, 'Teşkilat Kurulmadı', 'Sakarya', 'Sakarya', 'Sakarya'),
(806, 'Karapürçek', NULL, NULL, 'Birleştirildi', 'Akyazı', 'Sakarya', 'Sakarya'),
(807, 'Serdivan', NULL, NULL, 'Teşkilat Kurulmadı', 'Sakarya', 'Sakarya', 'Sakarya'),
(808, 'Söğütlü', NULL, NULL, 'Birleştirildi', 'Sakarya', 'Sakarya', 'Sakarya'),
(809, 'Taraklı', NULL, NULL, 'Birleştirildi', 'Geyve', 'Sakarya', 'Sakarya'),
(810, 'Salihli', 2, 'ACM', 'Faal', NULL, 'Salihli', 'Manisa'),
(811, 'Demirci', 3, 'Mülhakat', 'Faal', NULL, 'Salihli', 'Manisa'),
(812, 'Kula', 3, 'Mülhakat', 'Faal', NULL, 'Salihli', 'Manisa'),
(813, 'Selendi', 4, 'Mülhakat', 'Faal', NULL, 'Salihli', 'Manisa'),
(814, 'Köprübaşı (Salihli)', NULL, NULL, 'Birleştirildi', 'Salihli', 'Salihli', 'Manisa'),
(815, 'Samsun', 1, 'ACM', 'Faal', NULL, 'Samsun', 'Samsun'),
(816, 'Kavak', 4, 'Mülhakat', 'Faal', NULL, 'Samsun', 'Samsun'),
(817, 'Asarcık', NULL, NULL, 'Teşkilat Kurulmadı', 'Kavak', 'Samsun', 'Samsun'),
(818, 'Atakum', NULL, NULL, 'Teşkilat Kurulmadı', 'Samsun', 'Samsun', 'Samsun'),
(819, 'Canik', NULL, NULL, 'Teşkilat Kurulmadı', 'Samsun', 'Samsun', 'Samsun'),
(820, 'İlkadım', NULL, NULL, 'Teşkilat Kurulmadı', 'Samsun', 'Samsun', 'Samsun'),
(821, 'Tekkeköy', NULL, NULL, 'Birleştirildi', 'Samsun', 'Samsun', 'Samsun'),
(822, 'Seydişehir', 3, 'ACM', 'Faal', NULL, 'Seydişehir', 'Konya'),
(823, 'Beyşehir', 3, 'Mülhakat', 'Faal', NULL, 'Seydişehir', 'Konya'),
(824, 'Bozkır', 4, 'Mülhakat', 'Faal', NULL, 'Seydişehir', 'Konya'),
(825, 'Ahırlı', NULL, NULL, 'Birleştirildi', 'Bozkır', 'Seydişehir', 'Konya'),
(826, 'Derebucak', NULL, NULL, 'Birleştirildi', 'Beyşehir', 'Seydişehir', 'Konya'),
(827, 'Hüyük', NULL, NULL, 'Birleştirildi', 'Beyşehir', 'Seydişehir', 'Konya'),
(828, 'Yalıhüyük', NULL, NULL, 'Birleştirildi', 'Seydişehir', 'Seydişehir', 'Konya'),
(829, 'Siirt', 2, 'ACM', 'Faal', NULL, 'Siirt', 'Siirt'),
(830, 'Baykan', 5, 'Mülhakat', 'Faal', NULL, 'Siirt', 'Siirt'),
(831, 'Eruh', 5, 'Mülhakat', 'Faal', NULL, 'Siirt', 'Siirt'),
(832, 'Kurtalan', 4, 'Mülhakat', 'Faal', NULL, 'Siirt', 'Siirt'),
(833, 'Pervari', 5, 'Mülhakat', 'Faal', NULL, 'Siirt', 'Siirt'),
(834, 'Şirvan', 5, 'Mülhakat', 'Faal', NULL, 'Siirt', 'Siirt'),
(835, 'Tillo', NULL, NULL, 'Teşkilat Kurulmadı', 'Siirt', 'Siirt', 'Siirt'),
(836, 'Silifke', 2, 'ACM', 'Faal', NULL, 'Silifke', 'Mersin'),
(837, 'Gülnar', 4, 'Mülhakat', 'Faal', NULL, 'Silifke', 'Mersin'),
(838, 'Mut', 3, 'Mülhakat', 'Faal', NULL, 'Silifke', 'Mersin'),
(839, 'Silivri', 2, 'ACM', 'Faal', NULL, 'Silivri', 'İstanbul'),
(840, 'Çatalca', 2, 'Mülhakat', 'Faal', NULL, 'Silivri', 'İstanbul'),
(841, 'Sinop', 2, 'ACM', 'Faal', NULL, 'Sinop', 'Sinop'),
(842, 'Ayancık', 3, 'Mülhakat', 'Faal', NULL, 'Sinop', 'Sinop'),
(843, 'Gerze', 3, 'Mülhakat', 'Faal', NULL, 'Sinop', 'Sinop'),
(844, 'Türkeli', 4, 'Mülhakat', 'Faal', NULL, 'Sinop', 'Sinop'),
(845, 'Dikmen', NULL, NULL, 'Teşkilat Kurulmadı', 'Gerze', 'Sinop', 'Sinop'),
(846, 'Erfelek', NULL, NULL, 'Birleştirildi', 'Sinop', 'Sinop', 'Sinop'),
(847, 'Sivas', 1, 'ACM', 'Faal', NULL, 'Sivas', 'Sivas'),
(848, 'Divriği', 4, 'Mülhakat', 'Faal', NULL, 'Sivas', 'Sivas'),
(849, 'Gemerek', 4, 'Mülhakat', 'Faal', NULL, 'Sivas', 'Sivas'),
(850, 'Gürün', 4, 'Mülhakat', 'Faal', NULL, 'Sivas', 'Sivas'),
(851, 'İmranlı', 4, 'Mülhakat', 'Faal', NULL, 'Sivas', 'Sivas'),
(852, 'Kangal', 4, 'Mülhakat', 'Faal', NULL, 'Sivas', 'Sivas'),
(853, 'Şarkışla', 3, 'Mülhakat', 'Faal', NULL, 'Sivas', 'Sivas'),
(854, 'Yıldızeli', 4, 'Mülhakat', 'Faal', NULL, 'Sivas', 'Sivas'),
(855, 'Zara', 4, 'Mülhakat', 'Faal', NULL, 'Sivas', 'Sivas'),
(856, 'Altınyayla (Sivas)', NULL, NULL, 'Birleştirildi', 'Şarkışla', 'Sivas', 'Sivas'),
(857, 'Doğanşar', NULL, NULL, 'Birleştirildi', 'Sivas', 'Sivas', 'Sivas'),
(858, 'Hafik', NULL, NULL, 'Birleştirildi', 'Sivas', 'Sivas', 'Sivas'),
(859, 'Ulaş', NULL, NULL, 'Birleştirildi', 'Sivas', 'Sivas', 'Sivas'),
(860, 'Siverek', 3, 'ACM', 'Faal', NULL, 'Siverek', 'Şanlıurfa'),
(861, 'Hilvan', 5, 'Mülhakat', 'Faal', NULL, 'Siverek', 'Şanlıurfa'),
(862, 'Soma', 2, 'ACM', 'Faal', NULL, 'Soma', 'Manisa'),
(863, 'Kırkağaç', 3, 'Mülhakat', 'Faal', NULL, 'Soma', 'Manisa'),
(864, 'Söke', 2, 'ACM', 'Faal', NULL, 'Söke', 'Aydın'),
(865, 'Didim', 2, 'Mülhakat', 'Faal', NULL, 'Söke', 'Aydın'),
(866, 'Kuşadası', 2, 'Mülhakat', 'Faal', NULL, 'Söke', 'Aydın'),
(867, 'Sungurlu', 3, 'ACM', 'Faal', NULL, 'Sungurlu', 'Çorum'),
(868, 'Alaca', 3, 'Mülhakat', 'Faal', NULL, 'Sungurlu', 'Çorum'),
(869, 'Boğazkale', NULL, NULL, 'Birleştirildi', 'Sungurlu', 'Sungurlu', 'Çorum'),
(870, 'Şanlıurfa', 1, 'ACM', 'Faal', NULL, 'Şanlıurfa', 'Şanlıurfa'),
(871, 'Akçakale', 4, 'Mülhakat', 'Faal', NULL, 'Şanlıurfa', 'Şanlıurfa'),
(872, 'Bozova', 4, 'Mülhakat', 'Faal', NULL, 'Şanlıurfa', 'Şanlıurfa'),
(873, 'Harran', 5, 'Mülhakat', 'Faal', NULL, 'Şanlıurfa', 'Şanlıurfa'),
(874, 'Suruç', 4, 'Mülhakat', 'Faal', NULL, 'Şanlıurfa', 'Şanlıurfa'),
(875, 'Eyyübiye', NULL, NULL, 'Teşkilat Kurulmadı', 'Şanlıurfa', 'Şanlıurfa', 'Şanlıurfa'),
(876, 'Haliliye', NULL, NULL, 'Teşkilat Kurulmadı', 'Şanlıurfa', 'Şanlıurfa', 'Şanlıurfa'),
(877, 'Karaköprü', NULL, NULL, 'Teşkilat Kurulmadı', 'Şanlıurfa', 'Şanlıurfa', 'Şanlıurfa'),
(878, 'Şebinkarahisar', 3, 'ACM', 'Faal', NULL, 'Şebinkarahisar', 'Giresun'),
(879, 'Alucra', 4, 'Mülhakat', 'Faal', NULL, 'Şebinkarahisar', 'Giresun'),
(880, 'Koyulhisar', 4, 'Mülhakat', 'Faal', NULL, 'Şebinkarahisar', 'Sivas'),
(881, 'Suşehri', 4, 'Mülhakat', 'Faal', NULL, 'Şebinkarahisar', 'Sivas'),
(882, 'Akıncılar', NULL, NULL, 'Birleştirildi', 'Suşehri', 'Şebinkarahisar', 'Sivas'),
(883, 'Çamoluk', NULL, NULL, 'Birleştirildi', 'Alucra', 'Şebinkarahisar', 'Giresun'),
(884, 'Gölova', NULL, NULL, 'Birleştirildi', 'Suşehri', 'Şebinkarahisar', 'Sivas'),
(885, 'Şırnak', 3, 'ACM', 'Faal', NULL, 'Şırnak', 'Şırnak'),
(886, 'Beytüşşebap', 5, 'Mülhakat', 'Faal', NULL, 'Şırnak', 'Şırnak'),
(887, 'Uludere', 5, 'Mülhakat', 'Faal', NULL, 'Şırnak', 'Şırnak'),
(888, 'Tarsus', 2, 'ACM', 'Faal', NULL, 'Tarsus', 'Mersin'),
(889, 'Pozantı', 3, 'Mülhakat', 'Faal', NULL, 'Tarsus', 'Adana'),
(890, 'Çamlıyayla', NULL, NULL, 'Birleştirildi', 'Tarsus', 'Tarsus', 'Mersin'),
(891, 'Tatvan', 3, 'ACM', 'Faal', NULL, 'Tatvan', 'Bitlis'),
(892, 'Adilcevaz', 4, 'Mülhakat', 'Faal', NULL, 'Tatvan', 'Bitlis'),
(893, 'Ahlat', 4, 'Mülhakat', 'Faal', NULL, 'Tatvan', 'Bitlis'),
(894, 'Hizan', 5, 'Mülhakat', 'Faal', NULL, 'Tatvan', 'Bitlis'),
(895, 'Tavşanlı', 3, 'ACM', 'Faal', NULL, 'Tavşanlı', 'Kütahya'),
(896, 'Emet', 3, 'Mülhakat', 'Faal', NULL, 'Tavşanlı', 'Kütahya'),
(897, 'Harmancık (FD)', 4, 'Mülhakat', 'Birleştirildi', 'Tavşanlı', 'Tavşanlı', 'Bursa'),
(898, 'Domaniç', NULL, NULL, 'Birleştirildi', 'Tavşanlı', 'Tavşanlı', 'Kütahya'),
(899, 'Hisarcık', NULL, NULL, 'Birleştirildi', 'Emet', 'Tavşanlı', 'Kütahya'),
(900, 'Tekirdağ', 1, 'ACM', 'Faal', NULL, 'Tekirdağ', 'Tekirdağ'),
(901, 'Hayrabolu', 2, 'Mülhakat', 'Faal', NULL, 'Tekirdağ', 'Tekirdağ'),
(902, 'Malkara', 3, 'Mülhakat', 'Faal', NULL, 'Tekirdağ', 'Tekirdağ'),
(903, 'Muratlı', 3, 'Mülhakat', 'Faal', NULL, 'Tekirdağ', 'Tekirdağ'),
(904, 'Şarköy', 3, 'Mülhakat', 'Faal', NULL, 'Tekirdağ', 'Tekirdağ'),
(905, 'Süleymanpaşa', NULL, NULL, 'Teşkilat Kurulmadı', 'Tekirdağ', 'Tekirdağ', 'Tekirdağ'),
(906, 'Tokat', 2, 'ACM', 'Faal', NULL, 'Tokat', 'Tokat'),
(907, 'Almus', 4, 'Mülhakat', 'Faal', NULL, 'Tokat', 'Tokat'),
(908, 'Artova', 4, 'Mülhakat', 'Faal', NULL, 'Tokat', 'Tokat'),
(909, 'Erbaa', 3, 'Mülhakat', 'Faal', NULL, 'Tokat', 'Tokat'),
(910, 'Niksar', 3, 'Mülhakat', 'Faal', NULL, 'Tokat', 'Tokat'),
(911, 'Reşadiye', 4, 'Mülhakat', 'Faal', NULL, 'Tokat', 'Tokat'),
(912, 'Başçiftlik', NULL, NULL, 'Birleştirildi', 'Niksar', 'Tokat', 'Tokat'),
(913, 'Pazar (Tokat)', NULL, NULL, 'Birleştirildi', 'Tokat', 'Tokat', 'Tokat'),
(914, 'Sulusaray', NULL, NULL, 'Birleştirildi', 'Artova', 'Tokat', 'Tokat'),
(915, 'Yeşilyurt (Tokat)', NULL, NULL, 'Birleştirildi', 'Artova', 'Tokat', 'Tokat'),
(916, 'Torbalı', 1, 'ACM', 'Faal', NULL, 'Torbalı', 'İzmir'),
(917, 'Selçuk', 2, 'Mülhakat', 'Faal', NULL, 'Torbalı', 'İzmir'),
(918, 'Trabzon', 1, 'ACM', 'Faal', NULL, 'Trabzon', 'Trabzon'),
(919, 'Akçaabat', 2, 'Mülhakat', 'Faal', NULL, 'Trabzon', 'Trabzon'),
(920, 'Araklı', 3, 'Mülhakat', 'Faal', NULL, 'Trabzon', 'Trabzon'),
(921, 'Çaykara', 4, 'Mülhakat', 'Faal', NULL, 'Trabzon', 'Trabzon'),
(922, 'Maçka', 3, 'Mülhakat', 'Faal', NULL, 'Trabzon', 'Trabzon'),
(923, 'Of', 2, 'Mülhakat', 'Faal', NULL, 'Trabzon', 'Trabzon'),
(924, 'Sürmene', 2, 'Mülhakat', 'Faal', NULL, 'Trabzon', 'Trabzon'),
(925, 'Tonya', 4, 'Mülhakat', 'Faal', NULL, 'Trabzon', 'Trabzon'),
(926, 'Vakfıkebir', 2, 'Mülhakat', 'Faal', NULL, 'Trabzon', 'Trabzon'),
(927, 'Arsin', NULL, NULL, 'Birleştirildi', 'Trabzon', 'Trabzon', 'Trabzon'),
(928, 'Beşikdüzü', NULL, NULL, 'Birleştirildi', 'Vakfıkebir', 'Trabzon', 'Trabzon'),
(929, 'Çarşıbaşı', NULL, NULL, 'Birleştirildi', 'Vakfıkebir', 'Trabzon', 'Trabzon'),
(930, 'Dernekpazarı', NULL, NULL, 'Teşkilat Kurulmadı', 'Sürmene', 'Trabzon', 'Trabzon'),
(931, 'Düzköy', NULL, NULL, 'Birleştirildi', 'Akçaabat', 'Trabzon', 'Trabzon'),
(932, 'Hayrat', NULL, NULL, 'Teşkilat Kurulmadı', 'Of', 'Trabzon', 'Trabzon'),
(933, 'Köprübaşı (Trabzon)', NULL, NULL, 'Birleştirildi', 'Sürmene', 'Trabzon', 'Trabzon'),
(934, 'Ortahisar', NULL, NULL, 'Teşkilat Kurulmadı', 'Trabzon', 'Trabzon', 'Trabzon'),
(935, 'Şalpazarı', NULL, NULL, 'Birleştirildi', 'Vakfıkebir', 'Trabzon', 'Trabzon'),
(936, 'Yomra', NULL, NULL, 'Birleştirildi', 'Trabzon', 'Trabzon', 'Trabzon'),
(937, 'Tunceli', 3, 'ACM', 'Faal', NULL, 'Tunceli', 'Tunceli'),
(938, 'Hozat', 5, 'Mülhakat', 'Faal', NULL, 'Tunceli', 'Tunceli'),
(939, 'Mazgirt', 5, 'Mülhakat', 'Faal', NULL, 'Tunceli', 'Tunceli'),
(940, 'Nazımiye', 5, 'Mülhakat', 'Faal', NULL, 'Tunceli', 'Tunceli'),
(941, 'Ovacık (Tunceli)', 5, 'Mülhakat', 'Faal', NULL, 'Tunceli', 'Tunceli'),
(942, 'Pertek', 4, 'Mülhakat', 'Faal', NULL, 'Tunceli', 'Tunceli'),
(943, 'Pülümür', 5, 'Mülhakat', 'Faal', NULL, 'Tunceli', 'Tunceli'),
(944, 'Turgutlu', 2, 'ACM', 'Faal', NULL, 'Turgutlu', 'Manisa'),
(945, 'Ahmetli', NULL, NULL, 'Birleştirildi', 'Turgutlu', 'Turgutlu', 'Manisa'),
(946, 'Uşak', 1, 'ACM', 'Faal', NULL, 'Uşak', 'Uşak'),
(947, 'Banaz', 3, 'Mülhakat', 'Faal', NULL, 'Uşak', 'Uşak'),
(948, 'Eşme', 3, 'Mülhakat', 'Faal', NULL, 'Uşak', 'Uşak'),
(949, 'Simav', 3, 'Mülhakat', 'Faal', NULL, 'Uşak', 'Kütahya'),
(950, 'Sivaslı', 4, 'Mülhakat', 'Faal', NULL, 'Uşak', 'Uşak'),
(951, 'Karahallı', NULL, NULL, 'Birleştirildi', 'Sivaslı', 'Uşak', 'Uşak'),
(952, 'Pazarlar', NULL, NULL, 'Birleştirildi', 'Simav', 'Uşak', 'Kütahya'),
(953, 'Ulubey (Uşak)', NULL, NULL, 'Birleştirildi', 'Uşak', 'Uşak', 'Uşak'),
(954, 'Ünye', 2, 'ACM', 'Faal', NULL, 'Ünye', 'Ordu'),
(955, 'Akkuş', 5, 'Mülhakat', 'Faal', NULL, 'Ünye', 'Ordu'),
(956, 'Çaybaşı', NULL, NULL, 'Birleştirildi', 'Ünye', 'Ünye', 'Ordu'),
(957, 'İkizce', NULL, NULL, 'Birleştirildi', 'Ünye', 'Ünye', 'Ordu'),
(958, 'Van', 1, 'ACM', 'Faal', NULL, 'Van', 'Van'),
(959, 'Bahçesaray', 5, 'Mülhakat', 'Faal', NULL, 'Van', 'Van'),
(960, 'Başkale', 5, 'Mülhakat', 'Faal', NULL, 'Van', 'Van'),
(961, 'Çatak', 5, 'Mülhakat', 'Faal', NULL, 'Van', 'Van'),
(962, 'Gevaş', 4, 'Mülhakat', 'Faal', NULL, 'Van', 'Van'),
(963, 'Gürpınar', 4, 'Mülhakat', 'Faal', NULL, 'Van', 'Van'),
(964, 'Özalp', 5, 'Mülhakat', 'Faal', NULL, 'Van', 'Van'),
(965, 'Saray (Van)', 5, 'Mülhakat', 'Faal', NULL, 'Van', 'Van'),
(966, 'Edremit (Van)', NULL, NULL, 'Teşkilat Kurulmadı', 'Van', 'Van', 'Van'),
(967, 'İpekyolu', NULL, NULL, 'Teşkilat Kurulmadı', 'Van', 'Van', 'Van'),
(968, 'Tuşba', NULL, NULL, 'Teşkilat Kurulmadı', 'Van', 'Van', 'Van'),
(969, 'Vezirköprü', 3, 'ACM', 'Faal', NULL, 'Vezirköprü', 'Samsun'),
(970, 'Havza', 3, 'Mülhakat', 'Faal', NULL, 'Vezirköprü', 'Samsun'),
(971, 'Lâdik', 4, 'Mülhakat', 'Faal', NULL, 'Vezirköprü', 'Samsun'),
(972, 'Viranşehir', 3, 'ACM', 'Faal', NULL, 'Viranşehir', 'Şanlıurfa'),
(973, 'Ceylânpınar', 4, 'Mülhakat', 'Faal', NULL, 'Viranşehir', 'Şanlıurfa'),
(974, 'Yalova', 1, 'ACM', 'Faal', NULL, 'Yalova', 'Yalova'),
(975, 'Altınova', NULL, NULL, 'Teşkilat Kurulmadı', 'Yalova', 'Yalova', 'Yalova'),
(976, 'Çınarcık', NULL, NULL, 'Teşkilat Kurulmadı', 'Yalova', 'Yalova', 'Yalova'),
(977, 'Çiftlikköy', NULL, NULL, 'Teşkilat Kurulmadı', 'Yalova', 'Yalova', 'Yalova'),
(978, 'Termal', NULL, NULL, 'Teşkilat Kurulmadı', 'Yalova', 'Yalova', 'Yalova'),
(979, 'Yalvaç', 3, 'ACM', 'Faal', NULL, 'Yalvaç', 'Isparta'),
(980, 'Şarkikaraağaç', 3, 'Mülhakat', 'Faal', NULL, 'Yalvaç', 'Isparta'),
(981, 'Gelendost', NULL, NULL, 'Birleştirildi', 'Yalvaç', 'Yalvaç', 'Isparta'),
(982, 'Yenişarbademli', NULL, NULL, 'Birleştirildi', 'Şarkikaraağaç', 'Yalvaç', 'Isparta'),
(983, 'Yozgat', 2, 'ACM', 'Faal', NULL, 'Yozgat', 'Yozgat'),
(984, 'Akdağmadeni', 3, 'Mülhakat', 'Faal', NULL, 'Yozgat', 'Yozgat'),
(985, 'Çekerek', 4, 'Mülhakat', 'Faal', NULL, 'Yozgat', 'Yozgat'),
(986, 'Çiçekdağı (FD)', 4, 'Mülhakat', 'Birleştirildi', 'Yerköy', 'Yozgat', 'Kırşehir'),
(987, 'Sorgun', 3, 'Mülhakat', 'Faal', NULL, 'Yozgat', 'Yozgat'),
(988, 'Şefaatli', 4, 'Mülhakat', 'Faal', NULL, 'Yozgat', 'Yozgat'),
(989, 'Yerköy', 3, 'Mülhakat', 'Faal', NULL, 'Yozgat', 'Yozgat'),
(990, 'Akçakent', NULL, NULL, 'Birleştirildi', 'Yerköy', 'Yozgat', 'Kırşehir'),
(991, 'Aydıncık (Yozgat)', NULL, NULL, 'Birleştirildi', 'Çekerek', 'Yozgat', 'Yozgat'),
(992, 'Kadışehri', NULL, NULL, 'Birleştirildi', 'Çekerek', 'Yozgat', 'Yozgat'),
(993, 'Saraykent', NULL, NULL, 'Birleştirildi', 'Akdağmadeni', 'Yozgat', 'Yozgat'),
(994, 'Yüksekova', 3, 'ACM', 'Faal', NULL, 'Yüksekova', 'Hakkâri'),
(995, 'Şemdinli', 5, 'Mülhakat', 'Faal', NULL, 'Yüksekova', 'Hakkâri'),
(996, 'Derecik', NULL, NULL, 'Teşkilat Kurulmadı', 'Şemdinli', 'Yüksekova', 'Hakkâri'),
(997, 'Zile', 3, 'ACM', 'Faal', NULL, 'Zile', 'Tokat'),
(998, 'Turhal', 3, 'Mülhakat', 'Faal', NULL, 'Zile', 'Tokat'),
(999, 'Zonguldak', 1, 'ACM', 'Faal', NULL, 'Zonguldak', 'Zonguldak'),
(1000, 'Çaycuma', 3, 'Mülhakat', 'Faal', NULL, 'Zonguldak', 'Zonguldak'),
(1001, 'Devrek', 3, 'Mülhakat', 'Faal', NULL, 'Zonguldak', 'Zonguldak'),
(1002, 'Gökçebey', 4, 'Mülhakat', 'Faal', NULL, 'Zonguldak', 'Zonguldak'),
(1003, 'Kilimli', NULL, NULL, 'Teşkilat Kurulmadı', 'Zonguldak', 'Zonguldak', 'Zonguldak'),
(1004, 'Kozlu', NULL, NULL, 'Teşkilat Kurulmadı', 'Zonguldak', 'Zonguldak', 'Zonguldak');

SELECT setval('public.adliye_rehberi_id_seq', 1004, true);
